### ISSUE TITLE
Resolution scalling

### ISSUE THREAD

**Issue by benjamimgois** [vinifmor/bauh#1]
Hi Vinicius, 

Firstly congratulations for fpakman / Bauh ! It's a great and very important tool. I just want to report that the interface isn't scalling very well on 4K screens. The image speaks for it self.

(Screenshot attached )

![Captura de tela de 2019-08-13 23-29-27](https://user-images.githubusercontent.com/7688496/62990538-c4b6f180-be22-11e9-838e-6722983bd1d3.png)

**Comment by vinifmor** [comment]
Hi @benjamimgois, thank you. I will have a look here. What's your desktop environment ? I know in Gnome there are some missing icons when you install via **AUR**.  It seems to be a QT / PyQT missing dependency. Please, try to install manually using a **virtualenv** to see if the issue persists. In the project **README** there is a **Manual Installation** session.

**Comment by vinifmor** [comment]
Hi @benjamimgois . Version **0.8.1** is out fixing some HDPI and scaling issues. Could you give me a feedback if this release fixes your issues ? ( I'm currently with no HDPI device to test )

**Comment by benjamimgois** [comment]
Hi @vinifmor it definitely looks better than before, thanks for fixing hidpi ! I only see 2 things that still needs some tweaking:
- The font size on search field (too small).
- Fonte size on the combobox to select theme (also too small)
- Size of the icons and buttons to install / uninstall applications

Here is a screenshot.

![Captura de tela de 2020-01-15 01-15-06](https://user-images.githubusercontent.com/7688496/72404750-3d550d80-3735-11ea-8702-8539468c5f99.png)

**Comment by vinifmor** [comment]
Well, it definitely doesn't look as it should. Portuguese speaker ?

**Comment by benjamimgois** [comment]
Sim, sou brasileiro.

**Comment by vinifmor** [comment]
Maravilha. Então, um outro usuário chegou a abrir um PullRequest com algumas correções. Parece que no ambiente dele ficou ok. Vou deixar o link para você dar uma olhada: https://github.com/vinifmor/bauh/pull/43. 

Mas continuando... vamos tentar investigar o que pode ser. Hoje qual é o seu ambiente desktop e a versão ? Qual é a resolução do seu dispositivo ? Eu vou fazer uns testes aqui para ver se consigo descobrir o problema.

**Comment by benjamimgois** [comment]
Vinícius, dei uma verificada e parece que o problema está na escala de resolução do Gnome. Eu utilizo a versao 3.34.2, o desktop está em 3840x2160 com escala de resolução em 200%

![image](https://user-images.githubusercontent.com/7688496/72488412-ad27ce80-37ef-11ea-951e-0668b4103363.png)

Quando reduzi a escala para 100% parece que a interface normalizou.

![scale 100](https://user-images.githubusercontent.com/7688496/72488643-553d9780-37f0-11ea-8fb9-2e1405397667.png)

**Comment by benjamimgois** [comment]
Fiz mais alguns testes e o problema parece ser com aplicações QT em geral dentro do gnome. Veja como os ícones do avidemux (qt5) também apresentam problemas.

escala 100%
![avidemux 100](https://user-images.githubusercontent.com/7688496/72489349-9040ca80-37f2-11ea-9f38-94f851bc201c.png)

escala 200%
![avidemux 200](https://user-images.githubusercontent.com/7688496/72489367-99ca3280-37f2-11ea-8e09-634b2e7f9031.png)

**Comment by vinifmor** [comment]
Hum... interessante. Pode ser um bug do Gnome, alguma configuração ou alguma biblioteca do Qt que não está instalada. 

Se você inicia o bauh pelo terminal a 200%, ele exibe alguma mensagem de erro ? O scaling no KDE está funcionando bem a 1080p.

**Comment by vinifmor** [comment]
Encontrei esse artigo falando sobre esse problema -> https://unix.stackexchange.com/questions/433385/scaling-hidpi-issue-for-qt5-applications-under-gnome

Será que essa variável de ambiente resolve o problema ? Testa para mim no terminal, por favor:
`QT_AUTO_SCREEN_SCALE_FACTOR=1 bauh`

Se funcionar, eu posso procurar uma maneira de inclui-la no código a nível de aplicação.

**Comment by benjamimgois** [comment]
Desculpe a demora meu amigo, sua solução foi certeira. Funcionou perfeitamente !

![image](https://user-images.githubusercontent.com/7688496/72656229-b2fceb80-3978-11ea-9867-48e8738d2bba.png)

**Comment by vinifmor** [comment]
Tranquilo... que bom que funcionou. Então é um problema Gnome / QT. Eu vou ser se tem algum impacto negativo incluir essa variável direto no código. Se tiver, vou alertar no README do projeto para o pessoal que utiliza Gnome deixar essa variável disponível no sistema

**Comment by vinifmor** [comment]
@benjamimgois, eu adicionei uma nova configuração em que é possível ativar essa variável pelo próprio bauh. Você consegue acessar a opção na nova tela de configurações que vai entrar na 0.8.2. Eu publiquei uma RC com essa alterações no **bauh-staging** (AUR). 
![scaling_fix](https://user-images.githubusercontent.com/4312414/73487728-5d680c00-4386-11ea-9a0b-d59d7d489dba.png)

**Comment by benjamimgois** [comment]
Muito bom @vinifmor ! Funcionou perfeitamente.

**Comment by vinifmor** [comment]
Publiquei a release oficial no AUR ( 0.8.2 ). Vou fechar a issue. Obrigado por ter reportado o problema.
