### ISSUE TITLE
app list for install isn't updating? (0.5.2-1)

### ISSUE THREAD

**Issue by D33M0N** [vinifmor/bauh#10]
or does it require manual intervention from dev?

for example: Skype, in the startup says version 8.51.0.72 is available.
when I try to install, it fails cause it can't find version 8.50.0.38.
And in the AUR there is available already skyforlinux-stable-bin version 8.53.0.85-1.

anyway the install failed with this:
```
flatpak install flathub com.skype.Client -y

Looking for matches?
com.skype.Client permissions:
ipc	network	pulseaudio	x11
devices	file access [1]	dbus access [2]	system dbus access [3]
[1] home:ro, xdg-download
[2] org.freedesktop.Notifications, org.freedesktop.secrets, org.gnome.GConf,
org.gtk.Notifications, org.kde.StatusNotifierWatcher
[3] org.bluez, org.freedesktop.NetworkManager, org.freedesktop.login1
1.	   	com.skype.Client	x86_64	stable	flathub	< 74.6?MB
Installing?                                                                   
Installing? ??                     8%
Installing? ??                     8%
Error: While downloading https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb: Server returned status 404: Not Found
error: Failed to install com.skype.Client: While downloading https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb: Server returned status 404: Not Found

```

**Comment by vinifmor** [comment]
Hello @D33M0N , what seems to be happening here is that the Skype team published this update to Flathub with a bad source URL. If you try to retrieve this file (https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb) defined in this Flatpak, you will get an error.

It is not a **bauh** issue :)
