### ISSUE TITLE
Weird AUR failed install

### ISSUE THREAD

**Issue by Lennox84** [vinifmor/bauh#100]
Went to install an application called Turtl and bauh found the aur without a problem but when I went to install this is the log:

Found turtl-0.7.2.6-pre-sync-fix-linux64.tar.bz2
==> WARNING: Skipping verification of source file checksums.
==> Extracting sources...
-> Extracting turtl-0.7.2.6-pre-sync-fix-linux64.tar.bz2 with bsdtar
bsdtar: Failed to set default locale
==> Entering fakeroot environment...
==> Starting package()...
mkdir: cannot create directory '/root': Permission denied
./install.sh: line 43: /root/.config/turtl/install_location: Permission denied
mkdir: cannot create directory '/root': Permission denied
./install.sh: line 111: /root/.local/share/applications/turtl.desktop: Permission denied
==> ERROR: A failure occurred in package().
Aborting...
Could not find the built package. Aborting...
rm -rf /tmp/bauh/arch/build_1588149838

Installation logs can be found at "/tmp/bauh/logs/install/aur/turtl/1588149923.log"
Obviously it didn't install but wanted to confirm was this an issue with the AUR or something with bauh. I haven't installed this package on other Linux systems only Windows and OSX.
I haven't tried through pamac as seeing the /root creation requests makes me a bit sceptical of trying.

bauh version: 0.9.0
O.S Manjaro XFCE - 20.0
Python version: 3.8.2
Installation method (manual, package manager, ...): Through bauh package manager

**Comment by vinifmor** [comment]
Hi @Lennox84 . This package seems to execute a command that tries to create a dir at the system level (which is wrong). The correct way would be `mkdir ${pkdir}/my_directory`. I tried to install here with no success as well.

Have you had any trouble with other AUR packages ?

By the way... I recommend that you upgrade to version 0.9.1. There are important fixes related to Arch / AUR support ->  https://github.com/vinifmor/bauh/releases/tag/0.9.1

**Comment by Lennox84** [comment]
Hi Vin,

Yeah, I thought it was the package. Good to clarify.

No, I've had no issues with other packages so all good.
Apologies, I am running 0.9.1 I miss-typed.

Just curious but to avoid something like this happening with other packages
(Them trying to write to the wrong path or do something that could breach
security, would bauh be able to see that as it happens and flag, that way
the user would know and could possibly flag with the maintainer?) Just a
thought.
I'll reach out and share this with them as it didn't look right to me but
others may not look into it so deeply.

Anyway as always, thank you for all of your efforts, I use bauh exclusively
on all of my systems and appreciate your quick responses and the effort you
put into this application.
So the important question is how do I give you money for your efforts as I
genuinely appreciate what you're doing here 💪😀

Thanks again
Lennox

**Comment by vinifmor** [comment]
@Lennox84, the makepkg command  (used to build the AUR packages) is protected by default and cannot be executed with root privileges. This behavior prevents any sort of changes on the system structure. It is possible to detect simple scenarios if the wrong command is on the PKGBUILD declaration. In this particular case, the wrong `mkdir` command is not defined in the PKGBUILD itself (probably executed by one of the called scripts / programs ), so it would be harder to guess.

I'm glad bauh has been useful for you and it is your main option regarding GUIs for package management. I'm thinking about a possible way for people to contribute with the project. The money could go for the CI solution that is currently being used for automatizations (AppImage databases generation, apps categorizations, and other files that are published to [bauh-files (https://github.com/vinifmor/bauh-files/)). I'm using a free-plan, but it is limited. With a paid plan it would be possible to provide pre-built  AUR trusted packages for a faster installation, for instance. Anyway, I'm still thinking about the possibilities. When I have something concrete, I'm going to notify it via the bauh's Twitter account.

Cheers
