### ISSUE TITLE
The process of infinite initialization occurs.

### ISSUE THREAD

**Issue by Helg1980** [vinifmor/bauh#101]
![Screenshot_20200501_145353](https://user-images.githubusercontent.com/59513179/80807067-7a49f080-8bbc-11ea-9163-891c5aeb6883.png)

At startup, the process of infinite initialization occurs.

bauh version: 0.9.0, 0.9.1
O.S: Manjaro ver. 20

**Comment by vinifmor** [comment]
Please, launch bauh via command line (`bauh`) and paste any error log produced here. If none is displayed, try to reset bauh settings (`bauh --reset`) and launch it again (let me know if it works)

**Comment by Helg1980** [comment]
[helg@Houston ~]$ bauh --reset
[bauh] Cleaning configuration and cache files
[bauh] Deleting directory /home/helg/.cache/bauh
[bauh] Directory /home/helg/.cache/bauh deleted
[bauh] Deleting directory /home/helg/.config/bauh
[bauh] Directory /home/helg/.config/bauh deleted
[bauh][appimage] Deleting /home/helg/.local/share/bauh/appimage/releases.db
[bauh][appimage] /home/helg/.local/share/bauh/appimage/releases.db deleted
[bauh][appimage] Deleting /home/helg/.local/share/bauh/appimage/apps.db
[bauh][appimage] /home/helg/.local/share/bauh/appimage/apps.db deleted
[bauh] Cleaning finished
[helg@Houston ~]$ bauh
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/worker.py", line 121, in run
    saved += disk.save_several(pkgs, repo_map, when_prepared=self.update_prepared, after_written=self.update_indexed)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/disk.py", line 104, in save_several
    with open(file) as f:
FileNotFoundError: [Errno 2] There is no such file or directory: '/usr/share/sddm/themes/elarun/metadata.desktop'


I also tried reinstalling it, but it doesn't help either.

**Comment by vinifmor** [comment]
Right... I'm going to have a look here. For now if you want to use the tool, disable the Arch support through the settings window. The quickest way to open it is by typing `bauh --settings`. Thanks for the report.

**Comment by vinifmor** [comment]
@Helg1980 , I've published a possible fix for this issue in **bauh-staging** (0.9.2.RC-4) from AUR. Could you try it and give me a feedback if it works now ? Before launching bauh through the terminal, reset it again (`bauh --reset`).

**Comment by Helg1980** [comment]
Yes, everything works in the 0.9.2.RC-4 version .
Thank you very much!

**Comment by vinifmor** [comment]
No worries. The final 0.9.2 release should be available soon.

Cheers
