### ISSUE TITLE
Feature Request - Add option to enable or disable restart prompt

### ISSUE THREAD

**Issue by Finermeerkat137** [vinifmor/bauh#102]
Whenever I upgrade the system, there is a prompt asking me to restart. One option that might be a good idea is a setting in which you can enable or disable these prompts.

**Comment by vinifmor** [comment]
@Finermeerkat137 , **0.9.2** has just been released with this possibility. The release notes: https://github.com/vinifmor/bauh/releases/tag/0.9.2
