### ISSUE TITLE
Clicking on settings crashes the application. 

### ISSUE THREAD

**Issue by tulliana** [vinifmor/bauh#104]
![bauh-settings](https://user-images.githubusercontent.com/2324162/81088430-9a064f00-8f03-11ea-9574-8bc3a1d6d47c.png)
**Describe the bug**
Clicking on settings crashes the application. 
Application crashes when I click on Bauh settings. Terminal output and screenshot below.

**Software Environment**
**bauh version:** 0.9.2
**O.S:** Archman Linux (arch)
**Python version:** 3.8.2-2
**bauh installation method:** AUR repo

`[tulliana@tulliana-pc ~]$ 
![bauh-settings](https://user-images.githubusercontent.com/2324162/81088318-78a56300-8f03-11ea-9acf-cbbde6fe4500.png)
bauh
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/window.py", line 1237, in show_settings
    self.settings_window = SettingsWindow(self.manager, self.i18n, self.screen_size, self)
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/settings.py", line 29, in __init__
    self.settings_model = self.manager.get_settings(screen_size.width(), screen_size.height())
  File "/usr/lib/python3.8/site-packages/bauh/view/core/controller.py", line 422, in get_settings
    return self.settings_manager.get_settings(screen_width=screen_width, screen_height=screen_height)
  File "/usr/lib/python3.8/site-packages/bauh/view/core/settings.py", line 69, in get_settings
    tabs.append(self._gen_ui_settings(core_config, screen_width, screen_height))
  File "/usr/lib/python3.8/site-packages/bauh/view/core/settings.py", line 174, in _gen_ui_settings
    default_style = InputOption(label=cur_style, value=cur_style)
  File "/usr/lib/python3.8/site-packages/bauh/api/abstract/view.py", line 57, in __init__
    raise Exception("'label' must be a not blank string")
Exception: 'label' must be a not blank string
İptal edildi (çekirdek döküldü)
`

==========
Also, I did not see the option to install packages from my computer, i.e. locally. Only AppImage option available

**Comment by vinifmor** [comment]
@tulliana , I'm going to have a look here and publish a fix as soon as possible. Thanks for reporting the issue.

**Comment by vinifmor** [comment]
@tulliana , please post your bauh main config file here (```cat ~/.config/bauh/config.yml```)

**Comment by tulliana** [comment]
`[tulliana@tulliana-pc ~]$ cat ~/.config/bauh/config.yml
backup:
  downgrade: null
  enabled: true
  install: null
  mode: incremental
  type: rsync
  uninstall: null
  upgrade: null
disk:
  trim:
    after_upgrade: false
download:
  icons: true
  multithreaded: true
gems: null
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
store_root_password: true
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: false
  hdpi: true
  style: null
  table:
    max_displayed: 50
  tray:
    default_icon: null
    updates_icon: null
updates:
  ask_for_reboot: true
  check_interval: 30
[tulliana@tulliana-pc ~]$ 

`

**Comment by vinifmor** [comment]
@tulliana , try **bauh-staging** from AUR (0.9.3.RC-2) and let me know if it's working now

**Comment by tulliana** [comment]
Thanks mate.

Bauh-staging 0.9.3.RC-2 worked without any problems. 

I want to ask something else. I cannot see the local  Arch package installation option from my computer. Bauh only sees AppImage files.

**Comment by vinifmor** [comment]
No worries.. About your question: do you mean to install select and install a local Arch package ?
