### ISSUE TITLE
Bauh broken after Manjaro upgrade

### ISSUE THREAD

**Issue by technoshaman7777** [vinifmor/bauh#111]
**Describe the bug**
Bauh seemed to stop working after upgrade to Manjaro 20 over 2 weeks ago. I'll be the first to admit that I'm not a an advanced user of terminal, but can usually get by if I have clear instructions.

**Software Environment**
bauh version: bauh 0.9.3
O.S: Manjaro 20.0.1  linux kernel 5.5.19-1
Python version: 3.8.2-2
Gnome version: 3.36.2
Windowing System: X11
bauh installation method: manual --  pip3 install bauh

Here is what I have tried so far:
-uninstalling and reinstalling Bauh several times on Pamac, all versions listed one ata a time,  including- community, AUR, and testing branch.
Result:  icons are there, but click and nothing happens

-I've also tried restoring to earlier dates with Timeshift.
Result: still broken

-I've also cleared the Bauh cache.
Result: its says it's clean, but still doesn't work.

Manual Install to Virtual Env
Result: Hangs during install, shortlly after "collecting wheel metadata"

-Scour community blogs and resources for answers
Result; Your site is the only place I'm seeing any suggestions at all.

-Attempted PyPi install
Result: this one says installed, but when I run bauh I get this:
(I've also tried: python bauh    and get the same results) I also get the same results below if I run bauh-cli or bauh-tray.  Is my python broken?

[comp@comp-pc bin]$ bauh
Traceback (most recent call last):
  File "/home/comp/.local/bin/bauh", line 8, in <module>
    sys.exit(main())
  File "/home/comp/.local/lib/python3.8/site-packages/bauh/app.py", line 22, in main
    app_config = config.read_config(update_file=True)
  File "/home/comp/.local/lib/python3.8/site-packages/bauh/view/core/config.py", line 66, in read_config
    return read(FILE_PATH, default, update_file=update_file, update_async=True)
  File "/home/comp/.local/lib/python3.8/site-packages/bauh/commons/config.py", line 17, in read_config
    local_config = yaml.safe_load(f.read())
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 37, column 7:
      tray:

**Comment by vinifmor** [comment]
@technoshaman7777 , try this and let me know if it works:
```
bauh --reset && bauh
```

**Comment by technoshaman7777** [comment]
Getting the same thing:

yaml.scanner.ScannerError: mapping values are not allowed here

**Comment by vinifmor** [comment]
It seems something related to your bauh's config files. Have you manually changed them or just through the UI ?

**Comment by vinifmor** [comment]
What's your python-pyaml version ? `pacman -Q | grep python-pyaml`

**Comment by technoshaman7777** [comment]
python-pyaml 20.4.0-1

I haven't made any manual changes to the configs at all.

**Comment by vinifmor** [comment]
Could you attach your main bauh's config file here ? I'm going to test some scenarios.
The file is located at **~/.config/bauh/config.yml**

**Comment by technoshaman7777** [comment]
[config (copy).txt](https://github.com/vinifmor/bauh/files/4645404/config.copy.txt)

Can you download that? I renamed it with copy  and removed yaml for .txt. It wouldn't allow an upload of direct file.

**Comment by vinifmor** [comment]
I've downloaded here. It seems the file has a bad key and format. I've generated a default one and attached here as a zip file [config.yml.zip](https://github.com/vinifmor/bauh/files/4645926/config.yml.zip). Please, replace yours by it and let me know if bauh launches normally.

**Comment by technoshaman7777** [comment]
That worked, thank you very much. Just one question. I started an RSYNC backup when I tried to upgrade apps, but my Root drive is almost full. Is that a backup of just the apps it has installed, or is that a backup of the entire Root drive?

**Comment by vinifmor** [comment]
It generates a full backup of your root partition (**/**) using an external tool called Timeshift. You can manage the generated backups through Timeshift's UI

Are you using an Arch Linux distro ? If so, install bauh's through the AUR and the icons will be added. Otherwise, check the section **Manual installation** of bauh's README file. This section explains how you can add the desktop entries with the icon.

**Comment by technoshaman7777** [comment]
Fantastic! Everything works again. I already have Timeshift installed, and also had the packages for autosaving BTRFS snapshots incrementally installed prior to this installed via Pamac.  That should not cause any problems right? By enabling it on Bauh, it is just providing a UI to manage it? When it asks if I want to generate a system copy, will it copy the entire root over again, or will it just do an incremental backup under those circumstances? (I have limited space, so can't do full backup)

**Comment by vinifmor** [comment]
Bauh just asks Timeshift to generate a new backup based on your Timeshift's config. If you don't have a default config, Timeshift will generate a new one. The default backup mode is **incremental** and **Rsync**, but you can change it via settings (**Backup** tab). You can even completely disable bauh's backup integration if you prefer to manually manage your system's snapshots. All snapshots can be managed through the Timeshift CLI or UI

**Comment by vinifmor** [comment]
![backup_mode](https://user-images.githubusercontent.com/4312414/82454937-c46e1580-9a88-11ea-8e9e-d3aeb5d73055.png)

**Comment by technoshaman7777** [comment]
Thank you for all your help. This is a great project, and it keeps getting better!

**Comment by vinifmor** [comment]
No worries.  If you notice any more issues, report here so we can improve the tool.

Cheers
