### ISSUE TITLE
Distribute bauh as a Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [vinifmor/bauh#115]
I know that it is possible to install bauh using pip, but I think that it would be great if bauh could also be installed as a Flatpak. It would make the installation much easier for beginners. It would also make it possible to use bauh on immutable systems such as Fedora Silverblue. However, I am not sure if this is possible. It would probably require many changes to the bauh code and communication with flatpak/snap and other things would probably have to be done via dbus.

**Comment by vinifmor** [comment]
@AsciiWolf , I agree. I've already tried to generate a Flatpak version, but had a lot of permission problems and bauh ended up not working as it should. There is already an issue regarding this subject. I'm going to close this one and associate with the old one.
