### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pacman-mirrors'

### ISSUE THREAD

**Issue by tulliana** [vinifmor/bauh#117]
Bauh crashes when trying to update.

**Terminal output:**
`[tulliana@tulliana-pc ~]$ bauh
qt5ct: using qt5ct plugin
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1312, resource id: 12836198, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1746, resource id: 12837721, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 451, in run
    success = bool(self.manager.upgrade(requirements, root_password, self))
  File "/usr/lib/python3.8/site-packages/bauh/view/core/controller.py", line 248, in upgrade
    res = man.upgrade(man_reqs, root_password, handler)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 871, in upgrade
    if not self._upgrade_repo_pkgs(pkgs=repo_pkgs_names,
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 759, in _upgrade_repo_pkgs
    downloaded = self._download_packages(pkgs, handler, root_password, sizes)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 1638, in _download_packages
    return download_service.download_packages(pkgs=pkgnames,
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/download.py", line 123, in download_packages
    mirrors = pacman.list_available_mirrors()
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/pacman.py", line 1068, in list_available_mirrors
    _, output = system.run(['pacman-mirrors', '--status', '--no-color'])
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 278, in run
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Böyle bir dosya ya da dizin yok: 'pacman-mirrors'
İptal edildi (çekirdek döküldü)
`
**FileNotFoundError: [Errno 2] No such file or directory: 'pacman-mirrors'**

The mirror package is called **pacman-mirrors** but there is a mirrors file under **/etc/pacman.d/** directory. Bauh should search the mirror list as **mirrors**, not **pacman-mirrors**

**Comment by vinifmor** [comment]
@tulliana , **pacman-mirrors** is a program responsible for managing the mirrors set on your system. The real issue is that bauh is not validating if it is installed on your system. I'm going to provided a fix for this. For now you can either install **pacman-mirrors** or go to **Settings** > **Arch** and disable the option **Multi-threaded download (repositories)**

**Comment by vinifmor** [comment]
Already fixed that on **staging**. I'm going to publish to AUR in a few hours. If you want to check the changes -> https://github.com/vinifmor/bauh/commit/5901c4ceeacc27fad843b842d6fd9573915f6157

**Comment by vinifmor** [comment]
I've just published to AUR (**bauh-staging** > 0.9.5.RC-1). Could you give me a feedback if it is working now ?

**Comment by SamLukeYes** [comment]
> @tulliana , **pacman-mirrors** is a program responsible for managing the mirrors set on your system. The real issue is that bauh is not validating if it is installed on your system. I'm going to provided a fix for this. For now you can either install **pacman-mirrors** or go to **Settings** > **Arch** and disable the option **Multi-threaded download (repositories)**

As far as I know, `pacman-mirrors` is a Manjaro tool, and there's no way to install it on Arch Linux. A similar tool on Arch Linux is `reflector`.

**Comment by vinifmor** [comment]
Thanks for sharing this @SamLukeYes . I will have a look on **reflector**.
