### ISSUE TITLE
The problem with saving settings

### ISSUE THREAD

**Issue by kgudalov** [vinifmor/bauh#118]
**Describe the bug**
I usually disable Arch support, since I use Pamac for this. Recently, my saves stopped working, or rather they work the first time or two, and then they are enabled again by default. As a temporary solution, banning writing to the /.config/bauh/config.yml file helped
**Software Environment**
bauh version: 0.9.4
O.S: name and version Arch linux
Python version: 3.8.3
bauh installation method: manual / package manager  AUR

**Comment by vinifmor** [comment]
Hi, @kgudalov . I've noticed this behavior in 0.9.4. I'm going to publish a fix release as soon as possible.

**Comment by vinifmor** [comment]
@kgudalov , I've published a possible fix to the staging branch. It is available in AUR as **bauh-staging** (0.9.5.RC-2). Could you give me a feedback if the issue is fixed ?

**Comment by kgudalov** [comment]
@vinifmor 
Yes, everything works fine, thank you

**Comment by vinifmor** [comment]
Great. I'm going to publish the final 0.9.5 release in a few days.
