### ISSUE TITLE
Packet selection does not update when a program was uninstalled.

### ISSUE THREAD

**Issue by Dawoodoz** [vinifmor/bauh#119]
Packet selection from clicking or draging with left mouse button does not update correctly when a program was uninstalled. This looks like a bug in the visual component itself because it should have updated selection automatically when an item is removed. If I have four packets installed and uninstall the last of them, the following packet taking its place becomes selected. Not even sure what the blue selection is used for when you have to press buttons on packets individually.

**Software Environment**
bauh version: 0.9.3
O.S: Manjaro Linux 20.0.1 (Lysia)
Python version: 3.8
bauh installation method: I just found it pre-installed. Don't know if it came with the distro or as an automatic dependency to something.

**Comment by vinifmor** [comment]
The blue selection is currently only used for highlighting purposes on the current UI. The behavior you described is not considered an issue at the moment.
