### ISSUE TITLE
When I try to run bauh it complains about missing PyQt5.sip, despite it being installed.

### ISSUE THREAD

**Issue by perrsona1234** [vinifmor/bauh#123]
**Describe the bug**
When I try to run `bauh` it complains about missing `PyQt5.sip`, despite it being installed.

```
kris@brokenSUSE ~> bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib/python3.6/site-packages/bauh/app.py", line 5, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
ModuleNotFoundError: No module named 'PyQt5.sip'
kris@brokenSUSE ~> sudo pip3 install PyQt5
Requirement already satisfied: PyQt5 in /usr/lib64/python3.6/site-packages (5.15.0)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /root/.local/lib/python3.6/site-packages (from PyQt5) (12.8.0)
kris@brokenSUSE ~> 
```

**Software Environment**
bauh version: bauh-0.9.5
O.S: openSUSE Leap 15.2 RC (It's a Release Candidate, but I don't think this matters here, maybe lol)
Python version: 3.6
bauh installation method: From `pip` with `sudo pip3 install bauh`.

**Comment by vinifmor** [comment]
It should be a missing dependency on your system (e.g: python-sip). You can try the manual installation method as well. Have a look at the project's README file for instructions > https://github.com/vinifmor/bauh#manual-installation

**Comment by perrsona1234** [comment]
I installed the `python3-sip` package and now I'm getting a different error: 

```
kris@brokenSUSE ~> bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib/python3.6/site-packages/bauh/app.py", line 5, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
RuntimeError: the sip module implements API v12.0 to v12.7 but the PyQt5.QtCore module requires API v12.8
kris@brokenSUSE ~> 
```

Suprisingly, without the `python3-sip` package, I am able to run `bauh` as root:

```
brokenSUSE:/home/kris # bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib/python3.6/site-packages/bauh/app.py", line 5, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
RuntimeError: the sip module implements API v12.0 to v12.7 but the PyQt5.QtCore module requires API v12.8
brokenSUSE:/home/kris # zypper remove python3-sip
Odczytywanie zainstalowanych pakietów...
Rozwiązywanie zależności pakietu...

Następujący pakiet zostanie USUNIĘTY:
  python3-sip

1 pakiet do usunięcia.
Po wykonaniu operacji zwolnione zostanie 831,0 KiB.
Czy kontynuować? [t/n/w/...? wyświetla wszystkie opcje] (t): t
(1/1) Usuwanie python3-sip-4.19.19-lp152.1.7.x86_64 ....................................[gotowe]
 
brokenSUSE:/home/kris # bauh
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
```

**Comment by vinifmor** [comment]
Actually there is a separate sip implementation for Qt5. Check if you distro has a package named **python-pyqt5-sip** and uninstall the **python-sip**.

**Comment by perrsona1234** [comment]
From here https://repology.org/project/pyqt5-sip/versions I found that it's only packaged for Debian (-based) distros. I guess I will have to ask my distro maintainers to package it.

Should I close this now?

**Comment by vinifmor** [comment]
I see.. well, you can install it manually. It will bring all Python dependencies correctly in a separate virtual environment regardless of the distro. 

You can close it, since it is not a bauh issue.

**Comment by perrsona1234** [comment]
OK, thanks. I'm closing this one.
