### ISSUE TITLE
Can't install Cura AppImage

### ISSUE THREAD

**Issue by famewolf** [vinifmor/bauh#125]
**Describe the bug**
App downloads the cura appimage and then abends with an error saying a directory doesn't exist.

**Software Environment**
bauh version: 0.9.5 and 0.9.6-RC7
O.S: name and version Manjaro KDE (current)
Python version: 3.8.3
bauh installation method: manual / package manager   Pamac

Attempting to install cura results in this error even after manually creating the directory myself AND putting the appimage in it.

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 476, in install
    res, output = handler.handle_simple(SimpleProcess([file_path, '--appimage-extract'], cwd=out_dir))
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 77, in __init__
    self.instance = self._new(final_cmd, cwd, global_interpreter, lang, stdin=pwdin, extra_paths=extra_paths)
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 94, in _new
    return subprocess.Popen(cmd, **args)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/famewolf/.local/share/bauh/appimage/installed/cura-0-1/Cura-4.6.1.AppImage'

**Comment by vinifmor** [comment]
Hi. I could install and launch Cura normally on my end. Let's investigate what can be wrong. Please, launch bauh through the command line (`bauh`), re-install Cura and post here any error stack produced on your CLI and also those produced in the "Show details" console.

**Comment by famewolf** [comment]
Show Details:  
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3f650b|OK  |   842KiB/s|/home/famewolf/.local/share/bauh/appimage/installed/cura-0-1/Cura-4.6.1.AppImage
Status Legend:
(OK):download completed.
chmod a+x /home/famewolf/.local/share/bauh/appimage/installed/cura-0-1/Cura-4.6.1.AppImage

rm -rf /home/famewolf/.local/share/bauh/appimage/installed/cura-0-1

Installation logs can be found at "/tmp/bauh/logs/install/AppImage/Cura/1593033820.log
![Screenshot_20200624_172346](https://user-images.githubusercontent.com/4558832/85629527-0ff38080-b640-11ea-956a-fd1bad11ae85.png)
[1593033820.log](https://github.com/vinifmor/bauh/files/4827969/1593033820.log)


Console:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 476, in install
    res, output = handler.handle_simple(SimpleProcess([file_path, '--appimage-extract'], cwd=out_dir))
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 77, in __init__
    self.instance = self._new(final_cmd, cwd, global_interpreter, lang, stdin=pwdin, extra_paths=extra_paths)
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 94, in _new
    return subprocess.Popen(cmd, **args)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/famewolf/.local/share/bauh/appimage/installed/cura-0-1/Cura-4.6.1.AppImage'



"

**Comment by vinifmor** [comment]
Is **AppImageLauncher** installed on your system ? (or any kind of AppImage daemons) 

If so, uninstall it, reboot your system and try re-installing Cura.

**Comment by famewolf** [comment]
I uninstalled it the first time I tried to install cura because bauh indicated it prevented cura being installed. Not currently installed.  I'm willing to try a reboot.  Will report back.

**Comment by famewolf** [comment]
Worked fine after a reboot.  Typical.  Sorry for bothering you.

**Comment by vinifmor** [comment]
No worries. Generally after uninstalling a daemon/service it keeps running on the background.
