### ISSUE TITLE
Bauh UI icons not displayed

### ISSUE THREAD

**Issue by Anroch2020** [vinifmor/bauh#127]
Bauh UI icons are not displayed in archlinux
![Captura de pantalla de 2020-07-06 15-50-31](https://user-images.githubusercontent.com/67930062/86652550-c0974380-bfa1-11ea-8077-49418f8e953a.png)
Running bauh --logs don't show anything useful

**Software Environment**
Desktop Environment: Gnome 3.36.3
bauh version: 0.9.6-1
O.S: ArchLinux
Python version: 3.8.3-1
bauh installation method: Aur via yay

**Comment by vinifmor** [comment]
I believe it is something related to the system's global Qt theme. Try changing the bauh's style on settings (Interface tab).

**Comment by Anroch2020** [comment]
> I believe it is something related to the system's global Qt theme. Try changing the bauh's style on settings (Interface tab).

Solved installing qt5-svg

Archlinux wiki say:
> Since Qt 5.1 SVG support has moved into a module. Since qt5-base does not depend on qt5-svg it may happen that the qt5-base is installed but not qt5-svg. This results in deceptive icon theme behaviour. Since SVG is not supported the icons are silently skipped and the icon theme may seem to be unused. Installing qt5-svg explicitly solves the problem.
 
![Captura de pantalla de 2020-07-07 10-57-04](https://user-images.githubusercontent.com/67930062/86816079-a52f4580-c040-11ea-9eef-6a6fc977798a.png)

**Comment by vinifmor** [comment]
Great. I'm going to update the PKGBUILD including **qt5-svg** as a dependency.
