### ISSUE TITLE
What did it mean by search path?

### ISSUE THREAD

**Issue by kreezxil** [vinifmor/bauh#128]
I saw at the end of an installation that it said `/home/kreezxil/.local/share/flatpak/exports/share` wasn't in the search path.

Is this same as the $PATH variable?

**Software Environment**
bauh version: 0.9.6
O.S: Manjaro 20.0.3
Python version: 3.8.3
bauh installation method: package manager

**Comment by vinifmor** [comment]
@kreezxil , it seems this path is really not in $PATH, as you said. It is not in my device as well, but this message is not displayed for me. Try adding this path to $PATH and see if the message disappears.

**Comment by kreezxil** [comment]
it didn't go away is why i asked
I see it at the end of lots of flatpak installs

**Comment by vinifmor** [comment]
I'm going to investigate here. Is there any problem with the installed Flatpaks ?

**Comment by kreezxil** [comment]
no, i've detected no problems that i can see

**Comment by vinifmor** [comment]
I'm enforcing this path on the staging branch. Please, give me a feedback if the warning message has gone. You can install it through AUR as **bauh-staging** (0.9.7.RC3)

**Comment by kreezxil** [comment]
oh snap forgot to mention that I stopped using the stage branch. I'll
switch back to it. heads up tho, the main branch says it still. but i've
just learned to ignore it.

**Comment by vinifmor** [comment]
@kreezxil , now the stable (0.9.7) and staging (0.9.7.RC-17) packages have the same code.

**Comment by kreezxil** [comment]
ok nice
