### ISSUE TITLE
Native Web Applications not present in Archlinux?

### ISSUE THREAD

**Issue by Argenlos** [vinifmor/bauh#129]
Hello,

Cannot use Native Web Applications 
The option is not available in the settings either.
When I type a web address like in the documentation "https://github.com/vinifmor/bauh#native-web-applications--web-", I don't get any feedback from the interface.

I haven't found any information about this problem, if I can help it will be a pleasure, but you will have to guide me a little.
Thanks

Archilinux X86_64
bauh version: 0.9.6
O.S: Archlinux Rolling Release
Python version: Python 3.8.3
bauh installation method: package manager pamac

Regard,

Argenlos
![Screen Capture_select-area_20200714175823](https://user-images.githubusercontent.com/68291239/87448361-06848500-c5fc-11ea-8168-ed7943a2ede3.png)

**Comment by vinifmor** [comment]
Hello, @Argenlos . Probably your system is missing some dependencies the Web module requires to work. Are **python-lxml** and **python-beautifulsoup4** packages installed ? For more information, have a look at the section "Required dependencies" of https://github.com/vinifmor/bauh#native-web-applications--web-

**Comment by Argenlos** [comment]
Shame on me.
Python-beautifulsoup4 was missing.
Thank you for coming back.
Sorry for the inconvenience. Thank you very much for your time.
Argenlos

**Comment by vinifmor** [comment]
No worries... cheers!
