### ISSUE TITLE
Crash when upgrading openh264 flatpak 

### ISSUE THREAD

**Issue by TiLiNfIV** [vinifmor/bauh#130]
**Describe the bug**
Hi, after upgrading my system to the latest Stable branch release on Manjaro today, I experienced a crash on bauh when I wanted to Upgrade all Flatpak and AUR applications. I have found out that openh264 is causing the crash by process of elimination.

Here's the logs that I grabbed with journalctl : https://pastebin.com/CUDGhq1X

Here's a screenshot of bauh : 
![image](https://user-images.githubusercontent.com/58921348/87897065-35459580-ca18-11ea-8ec1-1fe1eb096c23.png)

Here's the result of `flatpak list` : 
    
    $ flatpak list
    Name                          Application ID                                 Version             Branch          Installation
    Bitwarden                     com.bitwarden.desktop                          1.18.0              stable          system
    Discord                       com.discordapp.Discord                         0.0.10              stable          system
    Skype                         com.skype.Client                               8.61.0.77           stable          system
    Slack                         com.slack.Slack                                4.4.3               stable          system
    Spotify                       com.spotify.Client                             1.1.26.501          stable          system
    Freedesktop Platform          org.freedesktop.Platform                       18.08.39            18.08           system
    Freedesktop Platform          org.freedesktop.Platform                       19.08.11            19.08           system
    default                       org.freedesktop.Platform.GL.default                                19.08           system
    html5-codecs                  org.freedesktop.Platform.html5-codecs                              18.08           system
    openh264                      org.freedesktop.Platform.openh264                                  19.08           system
    openh264                      org.freedesktop.Platform.openh264              2.1.0               2.0             system

I find it odd that there's two versions of openh264 installed. Could it be related to the issue?

**Software Environment**
bauh version: 0.9.6-1
O.S: Manjaro - Stable Branch 2020-07-19
Python version: 3.8.3
bauh installation method:  package manager

**Comment by Lennox84** [comment]
Apologies I should have raised this a while ago... had the same issue about 2 weeks ago. Updating through pacman in terminal fixed the issue and bauh has had no issues updating anything since.

Unsure if this was a package issue rather than a bauh issue... Just thought I'd add a little more background to this incase it's helpful.

Cheers, Len

**Comment by vinifmor** [comment]
@Lennox84 these two version are from different branches. Your installed Flatpaks probably require different versions of openh264. I'm going to investigate the crash reason. Thank you for letting me know.

**Comment by vinifmor** [comment]
Guys, I've fixed the issue. It is already on the staging branch -> https://github.com/vinifmor/bauh/commit/a02741284266176ef6de2c50252859eec454f450

In a few hours I'm going to publish to AUR (**bauh-staging** -> 0.9.7.RC-4)

**Comment by TiLiNfIV** [comment]
Cool! I won't be able to test though as I've upgraded the problematic package manually since then.

**Comment by vinifmor** [comment]
No worries. If it happens again, let me know.

**Comment by vinifmor** [comment]
This issue will be closed for now. If the problem happens again, please reopen it.
