### ISSUE TITLE
Suggestion: automatic parse '--classic' error and reinstall with --classic flag for snap packages

### ISSUE THREAD

**Issue by kanopeld** [vinifmor/bauh#135]
Error is:
```
sudo -S snap install app

error: This revision of snap "app" was published using classic confinement
and thus may perform arbitrary system changes outside of the security
sandbox that snaps are usually confined to, which may put your system at
risk.
If you understand and want to proceed repeat the command including
--classic.
Installation logs can be found at "/tmp/bauh/logs/install/snap/app/1600347685.log"
```

The best solution in this situation is to ask the user if he wants to install the application with the --classic flag and reinstall with --classic flag

**Comment by vinifmor** [comment]
Which bauh's version are you currently using ?

**Comment by kanopeld** [comment]
bauh 0.9.8

**Comment by vinifmor** [comment]
bauh automatically retrieves this info for every Snap and add the parameter if required. Are you still having issues ?

**Comment by vinifmor** [comment]
![bauh-snap-classic](https://user-images.githubusercontent.com/4312414/100894018-c59de780-349a-11eb-8e45-1b6b1e5cf928.png)
