### ISSUE TITLE
Suggestion: integrate rebuild-detector into bauh

### ISSUE THREAD

**Issue by AWHubGit** [vinifmor/bauh#139]
I love bauh! I was finally able to install ntopng by uninstalling and recompiling with bauh.
https://bbs.archlinux.de/viewtopic.php?id=33559
hiredis was updated, so needed to recompile ntopng.
With bauh recompiling was very easy. Excellent.

Here
https://bbs.archlinux.de/viewtopic.php?id=33080
it's suggested to use rebuild-detector
https://github.com/maximbaz/rebuild-detector
if a lot of AUR packages are used.

Please add (something like) rebuild-detector to bauh.
bauh should detect if recompilations are needed. 
Thanks for your great efforts. Very useful.

**Comment by vinifmor** [comment]
It would be very useful indeed. I'm going to add this suggestion to the backlog and think about the best to way to implement it.

**Comment by stefanhusmann** [comment]
There is not much to integrate. rebuild-detector acts as pacman hook, so it should be enough to just show pacman's output after installing.

**Comment by vinifmor** [comment]
Perhaps bauh could only display on the "Upgrade summary" the packages tp be rebuilt. I'm going to have a deeper look at this tool and see what sort of integrations could be done besides the console output.

**Comment by vinifmor** [comment]
**rebuild-detector** is integrated in the **staging** branch (already available in AUR as **bauh-staging**). Packages requiring to be rebuilt will be marked to update. More details at :https://github.com/vinifmor/bauh/blob/staging/CHANGELOG.md#features
