### ISSUE TITLE
[SUGGESTION] Dark mode for bauh?

### ISSUE THREAD

**Issue by perrsona1234** [vinifmor/bauh#141]
Hello.
Dark mode would be a nice addition to this tool, because I (and maybe most people out there) have all my system configured to use dark modes/themes/colors everywhere and `bauh` stands out from the crowd, like a sore thumb.
Thank You for all Your work.

**Comment by vinifmor** [comment]
Hi @perrsona1234 , I'm currently working exactly on that for the next minor release (0.9.9). It should be available soon.

**Comment by vinifmor** [comment]
By the way, what desktop environments are you currently using ?

**Comment by perrsona1234** [comment]
> By the way, what desktop environments are you currently using ?

Currently I'm using Cinnamon DE.

**Comment by perrsona1234** [comment]
Would it be also possible to implement a dark mode for webapps created with bauh?

**Comment by vinifmor** [comment]
bauh currently relies on nativefier to generate the WebApps. The current supported version (7.7.1) has a dark mode feature, but only for MacOSX. Perhaps in the future (I have to test the most recent version to check Linux support).

**Comment by vinifmor** [comment]
@perrsona1234 , the theming feature is ready. I've just released a new RC (0.9.9.RC-4) to the staging branch on AUR (**bauh-staging**). This new version features 2 dark themes by default:

- Darcula
<p align="center">
<img src="https://raw.githubusercontent.com/vinifmor/bauh-files/master/pictures/releases/0.9.9/darcula.png">
</p>

Sublime
<p align="center">
<img src="https://raw.githubusercontent.com/vinifmor/bauh-files/master/pictures/releases/0.9.9/sublime.png">
</p>

You can change the theme via the new button on the lower bar:
    <p align="center">
        <img src="https://raw.githubusercontent.com/vinifmor/bauh-files/master/pictures/releases/0.9.9/bt_themes.png">
    </p>

And you will be also able to create you own custom themes (more details about that on the final release).

If you are on Arch, try this RC and let me know any bugs or suggestions.

**Comment by perrsona1234** [comment]
I'm not on Arch, so I can't test it. But it looks dope, great work! Thanks :D

**Comment by vinifmor** [comment]
Just released **0.9.9** on PyPi. I'm going to close this issue.

Cheers
