### ISSUE TITLE
Trouble installing on Kubuntu

### ISSUE THREAD

**Issue by Lennox84** [vinifmor/bauh#142]
This isn't a bug as much of maybe me needing for help being a novice. I have installed with pip3 and can run bauh but I can't figure out how to add the Appimage ability. I know it has a GEMS title I can't see how to "install" GEMS (All I can find is GEMS are a ruby thing but can't see how that's useful to what I'm trying to do.

My install only allows me to install and update Snap. I really love bauh for the Appimage function set but it doesn't work out of the box here. I've installed on Manjaro and POP with zero issues but would love some help here to get it working on Kubuntu as this will be my daily driver moving forward

**Software Environment**
bauh version: 0.9.8
O.S: Kubuntu 5.4.0-52
Python version: 3.8.5
Installation method: pip & pip env

![image](https://user-images.githubusercontent.com/8501560/97098299-7a402e80-16cf-11eb-9225-de05105d5d00.png)

**Comment by vinifmor** [comment]
@Lennox84 , probably your Kubuntu is missing the AppImage required dependencies (there is a subtopic on the AppImage section). The package names vary from distro to distro, but what you need installed are **sqlite** and **wget**. As the project aims to react according to what is installed on your system, these packages cannot be marked as hard dependencies.

**Comment by Lennox84** [comment]
WooHoo!!! You absolute legend!

It was as easy as that, installed those 2 packages... well wget was already there so after sqlite installed I ran bauh and bingo, appimages available to install.

So just a thought but if bauh ran a check on 1st run, couldn't it detect what was missing if the user maybe wanted to access a feature and offer a list for the user to download?

-- 1st run bauh
--Check on system for correct packages to offer Flatpak & snap & appimage etc...
-- If items are missing, a window suggests something like = "bauh is capable of more than just snaps packages, to manage your appimages too please download e,y,z and restart bauh. If you don't want bauh to manage these for you, ignore this suggestion and continue" (But you can always run this check in settings if you want to give bauh a shot at managing your other package types)


Just a thought, I thought it would be pretty cool for newer users or ones just not super familiar with the whole linux landscape yet.

Either way, love your work as always.
Thanks heaps

Lenn

**Comment by vinifmor** [comment]
Great! I'm planning a sort of "warning" on the settings window (for instance, display the package type icon with a warning. And if you let your mouse over it, it would display "missing dependencies x, y, z". The trouble is: every distro has a specific name for each package. But it will be implemented in the future for sure.

Cheers
