### ISSUE TITLE
package bauh as appimage

### ISSUE THREAD

**Issue by Lvaskz** [vinifmor/bauh#144]
Hi, maybe you know all this advantages , but for beginners is much easier download and run an appimage.
thanks 
Providing an AppImage would have, among others, these advantages:
**Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)**
   
1. One app = one file = super simple for users: just download one AppImage file, make it executable, and run
2.     No unpacking or installation necessary
3.     No root needed
4.     No system libraries changed
5.     Works out of the box, no installation of runtimes needed
6.     Optional desktop integration
7.     Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
8.     Can optionally sign your AppImages (inside the file) using gpg2
9.     Works on Live ISOs
10.     Can use the same AppImages when dual-booting multiple distributions
11.     Can be listed in the AppImageHub central directory of available AppImages
12.     Can double as a self-extracting compressed archive with the --appimage-extract parameter
Here is an overview https://appimage.github.io/apps/of projects that are already distributing upstream-provided, official AppImages.

**Comment by vinifmor** [comment]
Hi @Lvaskz , I tried last year but was having some issues with non-Debian distros. I'm going to add this task to the backlog again. Help is welcome.

Cheers

**Comment by Lvaskz** [comment]
Thanks, maybe with this new tool can help ?
https://github.com/TheAssassin/appimagecraft

**Comment by vinifmor** [comment]
I'm going to have a look here. Thanks for the tip.

**Comment by vinifmor** [comment]
Done. First AppImage version can be downloaded from the releases page -> https://github.com/vinifmor/bauh/releases/tag/0.9.24.
I've also included in the bauh's AppImage database (should be available in a few hours)
