### ISSUE TITLE
no bauh anymore

### ISSUE THREAD

**Issue by AWHubGit** [vinifmor/bauh#149]
Arch Linux got a lot of updates [arch updates 02122020](https://github.com/AWHubGit/arch-updates_02122020/blob/main/index.txt)

Since then bauh doesn't start anymore:

bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 33, in <module>
    sys.exit(load_entry_point('bauh==0.9.8', 'console_scripts', 'bauh')())
  File "/usr/bin/bauh", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: bauh

Please fix asap.

Rgds
AW

**Comment by vinifmor** [comment]
Hello @AWHubGit , this issue is probably happening because the python version has been upgraded (from 3.8 to 3.9). Reinstalling bauh should solve this issue.

**Comment by AWHubGit** [comment]
Hi vinifmor

upgrading bauh strictly according to the Arch Linux AUR Guidelines
[AUR Guides](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages)

"In the directory containing the package's PKGBUILD you must first update the files and changes by using the command
$ git pull
then run
$ makepkg -si
to update the package." 

did the job.

Bauh 0.9.9 looks nice. Great! Thanks.

**Comment by vinifmor** [comment]
@AWHubGit , bauh already does that.  This issue already happened to me when Python upgraded from 3.7 to 3.8. For some reason it did not transfer the Python packages from 3.X for 3.X+1.

Good to hear that you were able to fix the issue and the tool is working again.

Cheers

**Comment by AWHubGit** [comment]
In a follow-up I parsed on my Arch Linux through the directory aur where all installed AUR packages are in. For all AUR packages I did a "git pull" and a "makepkg -si" (as per guidelines). There were other/further AUR packages not updated.

bauh should check for all AUR packages installed and throw (at least) warnings if not up to date.

**Comment by vinifmor** [comment]
This pacman hook you mentioned in the following issue [#139](https://github.com/vinifmor/bauh/issues/139) seems to check for upgraded programing languages and automatically recompiles packages that were previously built with different versions. As bauh just calls pacman, it should work for this scenario. I'm going to test it here.

**Comment by vinifmor** [comment]
@AWHubGit , now I got what you meant.  I thought was related to recompiling packages associated with Python or other programming languages. Today bauh only checks through the AUR Rest API. And you are right, for some cases, this method does not feet since not all packagers use the same version pattern. Please, open this thread as another issue.
