### ISSUE TITLE
Install local appimage [Feature]

### ISSUE THREAD

**Issue by DarkRB** [vinifmor/bauh#15]
Sometimes we may run across cases that we need a certain app that is not in the AppImagehub repository for download (https://appimage.github.io/apps/), but just lists there. 

Several examples like the app "TRuDI" ( i dont even know the use of the said app, but is a good example), that will not be shown in a search in Bauh, of course.

So i find the app there, and go to the git page of said app, download the appimage... now i dont really want to manage the appimage by myself, creating folders and stuff, so why not let Bauh manage it?

A "install local package" option would be great for such use-case. 

Thanks for the attention.

**Comment by vinifmor** [comment]
Hi @DarkRB . It is a good suggestion. I will add it to the backlog. Thank your for your feedback.

**Comment by Lennox84** [comment]
I'd like to +1 this as I've just gotten started using bauh and absolutely love it.
In my case I really want bauh to manage DigiKam and Bitwarden.
Bitwarden connector exists on Appimagehub but for some reason the Bitwarden client doesn't?? Really confused as to why they wouldn't release the actual application on hub, but it is the main download from their site.

I was surprised to not see DigiKam listed either, I will contact both teams and request info as to why they aren't on Appimagehub and direct my query in relation to my use and appreciation of buah and see if I get any info which could help us in the future to support more apps or get more apps listed on the hub.
Sorry for the long entry but I really love bauh and would like to help in any way possible and opening up its access of applications seems like a good starting point for now.

Thank you for building bauh!! I will continue to support in any way I can.

**Comment by vinifmor** [comment]
Hello @Lennox84, it is nice to see that you like and care for this project. This feature is on the backlog and should be implemented in the next months. The only drawback is that bauh will not be able to check for updates related to locally installed apps since it will not have access to their release catalog.

**Comment by vinifmor** [comment]
[#75](https://github.com/vinifmor/bauh/issues/75)

**Comment by lfom** [comment]
> Hello @Lennox84, it is nice to see that you like and care for this project. This feature is on the backlog and should be implemented in the next months. The only drawback is that bauh will not be able to check for updates related to locally installed apps since it will not have access to their release catalog.

Cool, maybe make them as "bauh" or another category instead of AppImage so it is clear that is should be updated manually?

By the way, how bauh updates AppImages: it does a full replace or only the deltas, like [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) does?

Kudos

**Comment by vinifmor** [comment]
@lfom , it is a good a idea to create a "Manual Update" category for them. Also their names could display something like "manually installed" or "imported. e.g: rpcs3 ( manually installed ) or postman ( imported )

In relation to how the updates are handled: bauh does the full file replacement, but does not remove saved data / configurations

**Comment by vinifmor** [comment]
Guys, this feature should be available in bauh **0.9.X**.

**Comment by vinifmor** [comment]
I finished to develop the file installation action. Some pictures:

![custom_actions](https://user-images.githubusercontent.com/4312414/76128165-54e89e00-5fe2-11ea-9021-7c054bef83f2.png)
![appimage_install](https://user-images.githubusercontent.com/4312414/76128172-587c2500-5fe2-11ea-8561-cb0632bafdea.png)
![appimage_listed](https://user-images.githubusercontent.com/4312414/76128178-5c0fac00-5fe2-11ea-9f56-f62f2552374e.png)

Now I'm going to implement the manual update process.

**Comment by Lennox84** [comment]
WooHoo!!

Looking good. Thanks for all your hard work Vin 💪

**Comment by vinifmor** [comment]
bauh **0.9.0** is out with this feature implemented. Detailed release notes: https://forum.manjaro.org/t/bauh-formerly-known-as-fpakman-a-gui-for-flatpak-and-snap-management/96180/167

Cheers

@DarkRB @Lennox84 @lfom

**Comment by lfom** [comment]
@vinifmor Awesome! Thanks for the heads up! I wi now ll report any bugs regarding manual AppImage installs if I find any. The only thing I had to do do after updating was edit the .desktop file I use to run bauh as `bauh --tray 1` does not work anymore. Keep it up!

**Comment by Lennox84** [comment]
Greats news thanks @vinifmor looking forward to updating my Manjaro build
and giving it a whirl.

Thanks again for all your hard work 💪💪💪💪

**Comment by vinifmor** [comment]
No worries, guys...  

@lfom , I've just simplified the tray parameter. You can either call it by passing just `--tray` or by calling `bauh-tray`. Any doubt, let me know

**Comment by lfom** [comment]
@vinifmor Yeah, I figured it out: after updating to 0.9.0 my app launcher wasn't working anymore, although it worked using the command in the Terminal. I think I worded it bad, it wasn't a complaining, more like I wanted to report the problem for anyone else with the same problem. I saw your not about the change, but it didn't say that the old command would cause any issues. Thanks again. Regards
