### ISSUE TITLE
Bug: appimage desktop files missing Exec params

### ISSUE THREAD

**Issue by gobonja** [vinifmor/bauh#152]
Exec params like fiedcodes (**%f** or **%u**), **--new-window**  etc are removed when parsing **Exec** value in desktop file.

This results in problems like opening external links in firefox.

Instead of replacing whole text with easiest solution might be to take text from **Exec=** to the first blank space and replace it with appimage path.

Best regards

**Comment by vinifmor** [comment]
I'm going to have a look here. Thanks for sharing this issue.

Best regards

**Comment by vinifmor** [comment]
@gobonja , I've just published the fix to the staging branch. Could you give me a feedback if it is working ? It is available on AUR as **bauh-staging** (0.9.10.RC-2)

**Comment by gobonja** [comment]
@vinifmor I can confirm that it is working in bauh-staging (0.9.10.RC-2)

Great work as always!

**Comment by vinifmor** [comment]
Great! Thanks for the feedback @gobonja
