### ISSUE TITLE
Can only load appimage from within bauh. Not from DE Application Launcher

### ISSUE THREAD

**Issue by Lennox84** [vinifmor/bauh#155]
**Before opening a new issue**
Install the **staging** branch and check if the unexpected behavior is happening there as well.
If you are on ArchLinux-based distro, you can install it through AUR (**bauh-staging**). Otherwise, you have
to clone the repository and install it with pip:
```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh  # or venv/bin/bauh-tray
```
 
**Describe the bug**
Appimage will install fine but it seems and cant be found in application launcher i.e. for etcher it reports "Could not find the program 'AppRun' & for GameHub 'com.github.tkashkin.gamehub'

**Software Environment**
bauh version: 0.9.10
O.S: name and version Fedora 33 (KDE Spin) 5.9.12-200.fc33.x86_64
Python version: Python 3.9.0
Installation method: pip | distro package manager (e.g: pacman)
Manual- Env
![Bauh screen 1](https://user-images.githubusercontent.com/8501560/101981638-8bb2b980-3cc2-11eb-8751-dcd5ca253a15.png)
![Bauh screen 2](https://user-images.githubusercontent.com/8501560/101981643-8c4b5000-3cc2-11eb-890b-ed0b77546be8.png)
![Bauh Etcher](https://user-images.githubusercontent.com/8501560/101981724-067bd480-3cc3-11eb-8acc-4a2775164f07.png)
![Bauh GH 2](https://user-images.githubusercontent.com/8501560/101981725-08459800-3cc3-11eb-87aa-a83afeb08638.png)
![Bauh GH](https://user-images.githubusercontent.com/8501560/101981726-08de2e80-3cc3-11eb-8406-61ba25df6da9.png)

P.S: these instructions and the template must be respected, otherwise your issue will be closed.

**Comment by vinifmor** [comment]
Hi @Lennox84 , thanks for sharing this issue. I'm going to have a look here. It can be a regression.

**Comment by vinifmor** [comment]
This issue is happening because now bauh respects the **Exec** command defined in the original desktop entry of the AppImage. 
RPCS3 does not face this issue. Anyway,  I'm going to add a solution for such cases to not harm the overall experience. Thanks again for the quick feedback.

**Comment by Lennox84** [comment]
Not a problem.
Glad you could discover the issue so quickly.

Amazing work as always Vin 💪

**Comment by vinifmor** [comment]
Thanks @Lennox84 . Issue already fixed. Please, try the **staging** branch again, and let me know if it is working now.

P.S: you need to reinstall these AppImages so bauh can regenerate the desktop entries.

**Comment by Lennox84** [comment]
Legend! Thanks.
I'll try it out later today and get back to you here 🤙🤙

**Comment by Lennox84** [comment]
Hi Vin,

Really sorry to be such a noob but now that I'm in Fedora and not Manjaro... How do I try the staging branch? Pip will install master no?

I'm following the Manual install instructions you have.
Cheers for your help

**Comment by Lennox84** [comment]
Hi Vin,

Really sorry to be such a noob but now that I'm in Fedora and not Manjaro... How do I try the staging branch? Pip will install master no?

I'm following the Manual install instructions you have.

**Comment by Lennox84** [comment]
Nevermind, figured it out WooHoo!!

All good, works like a charm.

Thanks
Vin!!

**Comment by vinifmor** [comment]
Great! I'll let this issue open for now until the final release is ready (so people can check if the problem is already reported).

Cheers
