### ISSUE TITLE
[Bug] appimage updates with continous releases are not getting registered

### ISSUE THREAD

**Issue by gobonja** [vinifmor/bauh#156]
Hi,

Appimages such as firefox has 4 tags under which updates are released and they are not gettng registered. However if I uninstall and install, again new version is installed.

[Firefox-Appimage](https://github.com/srevinsaju/Firefox-Appimage/releases)

I suppose bauh currently checks tags for releases.

Best regards

**Comment by vinifmor** [comment]
Hi @gobonja , I have to check out how AppImage Hub database deals with Firefox. I believe it just maps the stable version.

**Comment by vinifmor** [comment]
I know how to handle this. I'm going to change the upgrade script to publish "stable" releases as "stable-{date}", so bauh will be able to detect the updates.

**Comment by vinifmor** [comment]
Done. In a few a hours the AppImage database will be updated with this change. Give me a feedback if it works on your end.

**Comment by gobonja** [comment]
Sure will. Thanks!

**Comment by gobonja** [comment]
@vinifmor just go an update notification, updated it and it is working. 

Thanks again!

**Comment by vinifmor** [comment]
No worries. Thanks for sharing this issue. I'm going to close it now.
