### ISSUE TITLE
Flatpak system wide install fails

### ISSUE THREAD

**Issue by nigelwarning** [vinifmor/bauh#157]
**Describe the bug**
When I do a normal 'Flatpak install' in the terminal, it by default installs the flatpak system wide. During the install it will ask for a password, because it is a system install.
When I want to do a system wide install for the Flatpak 'Evolution' for example in Bauh, it doesn't work, because it won't ask for a password, so that means it can't install it. The bauh terminal thingy shows the following message:

Flatpak system operation Deploy not allowed for user

So command 'Flatpak install Evolution' works in the terminal, asks for the password and install it system wide (Which is default behaviour of Flatpak)

but installing it system wide on Bauh fauls, because I think not asking for the password.

**Software Environment**
bauh version: 0.9.10
O.S: name and version  Arch
Python version: 3.9
Installation method: AUR

P.S: these instructions and the template must be respected, otherwise your issue will be closed.

**Comment by vinifmor** [comment]
@nigelwarning , what's you Flatpak version ? This seems to be a new behavior on the latest Flatpak versions. I'm going to have a look here.

**Comment by vinifmor** [comment]
@nigelwarning , I've just tried to install two Flatpaks at the system level with bauh and had no issues. My Flatpak version is 1.9.2.

I'm going to attach the logs if you want to have a look: 
[flatpak_gedit.tar.gz](https://github.com/vinifmor/bauh/files/5711120/flatpak_gedit.tar.gz)
[flatpak_atom.tar.gz](https://github.com/vinifmor/bauh/files/5711122/flatpak_atom.tar.gz)

**Comment by nigelwarning** [comment]
I have the same problem with that one.

**Comment by nigelwarning** [comment]
Nevermind fixed it. I did something wrong in my Arch install and I was not in the 'wheels' group. Oops. Now works!

**Comment by vinifmor** [comment]
No worries. I'm going to close the issue then.

**Comment by digulla** [comment]
I just had the same issue on openSUSE LEAP 15.3.

Adding myself to the group ` wheels` (using `sudo usermod -a -G wheel $LOGNAME`) and uncommenting `%wheel ALL=(ALL) ALL` with `visudo` fixed it for me as well.

It would be nice when bauh would print an error message on openSUSE and Arch when the current user isn't in `wheels` and packages require ` system`  permissions. Otherwise, this is a pretty mysterious issue and hard to fix.
