### ISSUE TITLE
Not able to edit PKGBUILDs

### ISSUE THREAD

**Issue by RoestVrijStaal** [vinifmor/bauh#158]
Bauh v0.9.8
Manjaro Linux 20.2 

So I ticked "Edit PKGBUILD"-radio button to "Yes" (Actually it does not matter if choosing "Yes" or "Ask", because both result in an asking dialog) and marked an random AUR package as PKGBUILD-editable. However, No option to invoke an editor to edit the package's PKGBUILD pops up nor the Text Area within the "Package Info Dialog" is editable. 

What am I doing wrong?

**Comment by vinifmor** [comment]
Hi @RoestVrijStaal , the editor is only opened when you try to install a new package or upgrade/dowgrande a package marked as "PKGBUILD editable".

**Comment by RoestVrijStaal** [comment]
@vinifmor First thank you for your explaining answer.

I hoped that I could be able to "kick" an AUR-installed package to a new upstream version via bauh when its AUR-maintainer is absent for weeks. 

I could send a feature request for bauh. But still even then I need to figure out a different way to achieve the same for the time being 😅

**Comment by vinifmor** [comment]
@RoestVrijStaal I'm not sure if you actually could do it. AUR has some policies that must followed.

Just a tip: use the bauh version from AUR. I personally keep it.  It seems your distro maintainers are not updating the package (latest version is **0.9.10** and I'm going to publish **0.9.11** before the year ends).
