### ISSUE TITLE
[Bug] firefox appimage is always downloading nightly version

### ISSUE THREAD

**Issue by gobonja** [vinifmor/bauh#159]
Hi,

Not sure what happened here but I think they changed release tags. So now it always downloads nightly version.

![image](https://user-images.githubusercontent.com/26535797/103087843-1fe91e80-45e9-11eb-9a65-3ab3188e1dbf.png)

Tested on both bauh and bauh-staging.

Best regards

**Comment by vinifmor** [comment]
Hi @gobonja , thanks for sharing this issue. I'm going to have a look here.

Regards

**Comment by vinifmor** [comment]
@gobonja , already fixed. In a few hours the database should be updated.
![firefox_bauh](https://user-images.githubusercontent.com/4312414/103092817-469e5980-45d7-11eb-9adf-dce442c2b166.png)

Please, give me a feedback later.

**Comment by vinifmor** [comment]
Click on the info button button (?) to check the file.

**Comment by gobonja** [comment]
Works like a charm!

Thanks again

**Comment by vinifmor** [comment]
No worries... thanks for sharing this.
