### ISSUE TITLE
Suggestion. Could you bauh create an appimage from a package installed on the system?

### ISSUE THREAD

**Issue by Predatux** [vinifmor/bauh#162]
Suggestion. Could you bauh create an appimage from a package installed on the system?
I have not found any simple way to create an appimage package. I would like to know if it is possible to automate a way to create an appimage from a package installed on the system.

**Comment by vinifmor** [comment]
Hi @Predatux , unfortunately create AppImages is not a simple process and demands human interaction to be properly done. Bauh just adds features that demand little or none human interaction. Thanks for the suggestion anyway.
