### ISSUE TITLE
missing input/interaction for resolving conflicts

### ISSUE THREAD

**Issue by AWHubGit** [vinifmor/bauh#165]
I get this message from bauh:
resolving dependencies...
looking for conflicting packages...
:: pulseaudio and pipewire-pulse are in conflict. Remove pipewire-pulse? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pulseaudio and pipewire-pulse are in conflict

Nothing else happens.

What can I do? No input possible for "yes or no". There should be an input option in bauh for this. And this message should also be shown when not looking at the detailled log. Does bauh just abort, when arriving at this stage? It should tell it when aborting or exiting with errors.

Rgds
AW

**Comment by vinifmor** [comment]
@AWHubGit , bauh already displays a dialog when there is a conflict (it may me a bug related to a specific scenario). For instance, this picture below shows the dialog when an user is trying to install **bauh** when **bauh-staging** is already installed:
![bauh_conflict](https://user-images.githubusercontent.com/4312414/104585318-9904f000-5642-11eb-88ae-a86e00683212.png)

What version of bauh are you currently using ? Could you give me more details about the scenario (were you upgrading several packages, or installing a new one ?)
