### ISSUE TITLE
Missing dependency - ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Andriamanitra** [vinifmor/bauh#169]
Fix for #167 added a dependency which doesn't get installed automatically when following the manual installation instructions.

```bash
$ python3 -m venv bauh_env
$ bauh_env/bin/pip install bauh
$ bauh_env/bin/bauh
Traceback (most recent call last):
[...]
  File "/home/mikko/bauh_env/lib/python3.9/site-packages/bauh/gems/flatpak/controller.py", line 10, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

Running `bauh_env/bin/pip install packaging` fixes the issue.

**Comment by vinifmor** [comment]
Hi @Andriamanitra , thanks for the quick feedback. I'm going to publish the fix ASAP.

**Comment by vinifmor** [comment]
**0.9.13** released adding **packaging** to **requirements.txt**
