### ISSUE TITLE
Multiple package selections to install

### ISSUE THREAD

**Issue by SparkyCandle** [vinifmor/bauh#171]
It's cumbersome to install one software at a time. It would be nice if we can tick 2 or more packages to install at the same time. till then i have to do `yay package1 .... package10`
edited due spelling errors

**Comment by vinifmor** [comment]
Hi @SparkyCandle , this feature is already on the backlog and was also suggested in [#153](https://github.com/vinifmor/bauh/issues/150). I'm going to close this one and associated with #150.
