### ISSUE TITLE
qt5ct support gone?

### ISSUE THREAD

**Issue by lfom** [vinifmor/bauh#176]
**Describe the bug**
Hello, again! Two small things:

1) There is no more support for _qt5ct_?

2) ~~Using the "default" theme breaks icons~~

**Software Environment**
bauh version: 0.9.16
O.S: Pop!_OS 20.10 (like Ubuntu 20.10)
Python version: 3.7.8
Installation method: pip

![2021-04-07_04-16](https://user-images.githubusercontent.com/15659999/113826337-6d346a80-9758-11eb-8513-2a3a07ebebeb.png)

**Comment by vinifmor** [comment]
Hi @lfom, the main 3 style sheets provided (light, sublime, darcula) have some strict Qt rules that cannot be overwritten easily (some of them are possible, but you have to enable **System theme** on the **Interface** settings). The reason for that, is to provide a single look across different systems and Qt configurations.

The best way to customize the appearance is to provide your own theme. Have a look at: [Custome themes](https://github.com/vinifmor/bauh#custom_themes)

About the icons: I've tested here on my end using the default distro Qt theme (Breath), and they are showing up normally. It is possible that your system has a missing configuration.

**Comment by lfom** [comment]
I did not notice the menu to change the theme, so I was editing the config manually and I saw a folder named "default" in the repo, that is why I tried to use the theme. Probably it is just a support folder, right? So everything seems fine.

Enabling or disabling "System theme" does not seem to make any difference here, I was thinking it should make the app follow the system settings for Qt, but that is fine. The darcula theme should work for me for now, it is close enough to Nord.

Thanks for your continuous support to the app. A centralized way to manage third party apps is very nice.

Regards

**Comment by vinifmor** [comment]
No worries. Thanks for reporting you use case. Perhaps bauh could provide a theme called "system" that just grab the base style structure, merging with the system definitions.

**Comment by lfom** [comment]
I am not sure about what System Theme was supposed to do (as I said, it does not seem to change anything here), but how about disabling builtin-in themes and use whatever QT_QPA_PLATFORMTHEME is defined when it is enabled and the use the themes and the two options of interface when it isn't? If you plan to implement this I can leave the issue open and test when it is released.

**Comment by vinifmor** [comment]
I'm going to test this variable and see the impact. Let the issue open for now.

**Comment by lfom** [comment]
Maybe this info helps:
- when it is not set, it uses the default theme (Fusion IIRIC)
- gtk2 is a buliltin option that tries to inherit the GTK theme but it is deprecated AFAIK
- the most common use is qt5ct, a configuration utility that can be uses to configure the theme, and one of its options if to use use the GTK theme

**Comment by vinifmor** [comment]
Thanks @lfom

**Comment by lfom** [comment]
It is working perfectly now. It even inherits correctly the system theme colors when the option is enable, regardless of the style selected. Thanks!
`bauh` 0.9.18 on Pop!_OS 21.04 (like Ubuntu 21.04)

Thanks!

![Screenshot from 2021-08-15 16-26-41](https://user-images.githubusercontent.com/15659999/129490154-369ee161-2d9d-4226-887f-da0dbd66e567.png)
