### ISSUE TITLE
AppImage database files were not found. Some actions will not work properly.

### ISSUE THREAD

**Issue by winuxwinfree** [vinifmor/bauh#180]
Error MSG: AppImage database files were not found. Some actions will not work properly.

Maybe it's because I launch the program from .local/bin instead of adding the PATH
I'm using debian.

 WARNING: The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/home/usuario/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts bauh, bauh-cli and bauh-tray are installed in '/home/usuario/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by winuxwinfree** [comment]
I don't know how to add bauh to PATH

**Comment by DN-debug** [comment]
> I don't know how to add bauh to PATH

To add the path, you'd simply export it to the $PATH variable

`export PATH="path to your program":$PATH`

To check the paths, you would simply do: `echo $PATH`

Hope that helps.

**Comment by winuxwinfree** [comment]
Thanks DN-Debug

This is what I put and I still have the problem:
export PATH="/home/usuario/.local/bin/bauh:$PATH"
Sorry for my ignorance.

**Comment by winuxwinfree** [comment]
Thanks DN-Debug

This is what I put and I still have the problem:
export PATH="/home/usuario/.local/bin/bauh:$PATH"

Maybe some dependency is missing or I have to add some path before installing it. Python?

Dependences that I have:
sudo apt-get install python3 python3-pip python3-yaml python3-dateutil python3-pyqt5 python3-packaging python3-requests
sudo apt-get install qt5-default pyqt5-dev pyqt5-dev-tools
sudo apt install python-lxml

I tried the same thing in Debian and Ubuntu and other ways, so I think I must not be the only one. I looked on many pages where it says how to install bauh and I can't find something I haven't tried.
Sorry for my ignorance.

**Comment by DN-debug** [comment]
> Thanks DN-Debug
> 
> This is what I put and I still have the problem:
> export PATH="/home/usuario/.local/bin/bauh:$PATH"
> 
> Maybe some dependency is missing or I have to add some path before installing it. Python?
> 
> Dependences that I have:
> sudo apt-get install python3 python3-pip python3-yaml python3-dateutil python3-pyqt5 python3-packaging python3-requests
> sudo apt-get install qt5-default pyqt5-dev pyqt5-dev-tools
> sudo apt install python-lxml
> 
> I tried the same thing in Debian and Ubuntu and other ways, so I think I must not be the only one. I looked on many pages where it says how to install bauh and I can't find something I haven't tried.
> Sorry for my ignorance.

Dont be sorry when u are learning things.

Your path is incorrect. You should not include the program, but the path to program. So, in this case only till /bin:

` export PATH="$HOME/.local/bin/:$PATH"` and then check whether it got added or not `echo $PATH`.

If the appimage has been installed properly, then you should be able to see the entry in  your "$HOME/.local/share/bauh/appimage/installed/" directory and the executable in "$HOME/.local/bin/" directory. 

Beside, I am a lil' confused. You said "Appimage", so is it a program that you tried installing but didn't work or is it Bauh that's not working as a whole?

**Comment by winuxwinfree** [comment]
Thank you very much DN-debug 
I get this message every time I run the program. And I can't find any options in the menus related to the AppImage.
I tried the last command you told me but it doesn't fix it:
export PATH="$HOME/.local/bin:$PATH"

**Comment by winuxwinfree** [comment]
The database files apps.db and releases.db are not in ~/.cache/bauh/appimage, in fact the folder appimage does not exist, there is only a folder called web.

**Comment by DN-debug** [comment]
> The database files apps.db and releases.db are not in ~/.cache/bauh/appimage, in fact the folder appimage does not exist, there is only a folder called web.

Do you have the dependencies installed that Bauh requires to make Appimages to work? I mentioned those dependencies in my previous reply.

**Comment by winuxwinfree** [comment]
Thanks DN-debug, it's working.
I just modified the path and installed sqlite3 and fuse.

**Comment by winuxwinfree** [comment]
Thanks DN-debug, it's working!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I just modified the path and installed sqlite3 and fuse.

**Comment by winuxwinfree** [comment]
Thanks DN-debug, it's working!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I just modified the path and installed sqlite3 and fuse.
