### ISSUE TITLE
AppImage File Chooser Dialog ignores "appname.appImage"

### ISSUE THREAD

**Issue by lfom** [vinifmor/bauh#185]
**Before opening a new issue**
Install the **staging** branch and check if the unexpected behavior is happening there as well.
If you are on ArchLinux-based distro, you can install it through AUR (**bauh-staging**). Otherwise, you have
to clone the repository and install it with pip.

_Done, the problem persists_

**Describe the bug**

_File picker for AppImage ignores other cases for file extension, like **appname.appImage** or **appname.appimage**. It would be nice if it was case insensitive or includes most common cases, at least. Or perhaps include a "All Files" filter to show any file, and do some checking if the file is actually an AppImage_.

**Software Environment**
bauh version: _0.9.18_
O.S: _Pop!_OS 21.04 (like Ubuntu 21.04)_
Python version: _Pyhton 3.9.5_
Installation method: _pip_ 

Once again, thanks a lot for `bauh`.
Regards

**Comment by vinifmor** [comment]
@lfom it works for KDE (at leat) independently of the case like the picture below shows:
![bauh_appimage](https://user-images.githubusercontent.com/4312414/130324356-9fccc5e8-c837-4d2f-9c66-02d9da606dd7.png)

But I will have a look if there is a property that could force the case to be ignored.

**Comment by lfom** [comment]
@vinifmor Hmm... For some reason, it seems that on Gnome (at least on Pop!_OS) it uses a GTK-based file dialog, and filters are case sensitive.

![Screenshot from 2021-08-21 12-25-04](https://user-images.githubusercontent.com/15659999/130326788-b31094b5-d835-4948-9c2b-eb818e02a1fe.png)

**Comment by vinifmor** [comment]
Added a generic filter (.*) for this cases. Already on **staging**.
