### ISSUE TITLE
feature: able to install AUR packages when running as root

### ISSUE THREAD

**Issue by edmundlaugasson** [vinifmor/bauh#196]
**Describe the bug**
bauh tries run yay as root and fails  when installing app from AUR.
![Screenshot_20210917_005348](https://user-images.githubusercontent.com/6355082/133690755-8575b801-a982-49ca-93e8-2c5fe27ba78e.png)
Tried `bauh --reset` but didn't help.

**Software Environment**
bauh version: 0.9.19-1
O.S: Endeavour OS (rolling release), KDE
Python version: 3.9.7
Installation method: pacman

**Comment by vinifmor** [comment]
Hello @edmundlaugasson , bauh does not use **yay** as the AUR backend (it has its own implementation). **makepkg** does not allow to build/compile packages as root by default (this warning is to prevent the error). I'm going to have a look if it is possible someway.

**Comment by vinifmor** [comment]
I've just pushed a solution for this feature on the **staging** branch (**bauh-staging** package on **AUR** )
