### ISSUE TITLE
TypeError: setMinimumWidth(self, int) argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by AWHubGit** [vinifmor/bauh#198]
I am trying to install "bauh" in Fedora 35 prerelease running as VM in virtenv "Boxes" in a ArchLinux.
python3-pyqt5-sip-12.9.0-2.fc35.x86_64 has been manually installed by "sudo dnf install python3-pyqt5-sip".

Using "pip install bauh" leads to a "TypeError: setMinimumWidth(self, int) argument 1 has unexpected type 'float'" when trying to start bauh on cli.
pip uninstall bauh 
Building/installing bauh according to:
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh  # or venv/bin/bauh-tray

is not possible.

venv/bin/pip install -r requirements.txt throws error:
 ----------------------------------------
ERROR: Failed building wheel for PyQt5-sip
Failed to build PyQt5-sip
ERROR: Could not build wheels for PyQt5-sip which use PEP 517 and cannot be installed directly

How to install now bauh?

**Comment by vinifmor** [comment]
I'm going to try installing on Fedora and let you know. It should be a missing package.

**Comment by manuGe** [comment]
Are there any updates? I'm running Fedora 35 and can't run bauh anymore.
Installing bauh with `pip install bauh` works flawlessly but when I try to start the application from the terminal, I'm getting the following error message:
```
Traceback (most recent call last):
  File "/home/manuel/.local/bin//bauh", line 8, in <module>
    sys.exit(main())
  File "/home/manuel/.local/lib/python3.10/site-packages/bauh/app.py", line 51, in main
    app, widget = new_manage_panel(args, app_config, logger)
  File "/home/manuel/.local/lib/python3.10/site-packages/bauh/manage.py", line 70, in new_manage_panel
    prepare = PreparePanel(screen_size=app.primaryScreen().size(),
  File "/home/manuel/.local/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 156, in __init__
    self.setMinimumWidth(screen_size.width() * 0.5)
TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'
```

**Comment by vinifmor** [comment]
That's weird. It seems the QT libraries for Fedora are no casting float to integers. Anyway, I've pushed a hard casting for the QT component sizes to avoid this sort of issue https://github.com/vinifmor/bauh/commit/b50b067158e18e50726b01bee598d7ffd50add25 on the **staging** branch. Could you give me a feedback if it is not crashing anymore ?

**Comment by manuGe** [comment]
Works perfectly now. Thanks for the quick fix!
