### ISSUE TITLE
snapd seems not to be installed or enabled

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#20]
When I have installed snapd, but not enabled it, I see warning

> snapd seems not to be installed or enabled. Snap packages will not be available

It would be helpful to distinguish between installed vs enabled, which is trivial in the common case of looking for `snapd` or the systemctl .service.  Also 'started' is probably a better term than 'enabled', as enabled in systemctl means the service is part of the service list, but it can be stopped while enabled, and it will be started again on the next restart.

If found but not started, it would be helpful to remind the user to run `systemctl start snapd`, as many users forget systemctl syntax.

**Comment by vinifmor** [comment]
The thing is: this behavior is different depending on the Linux distro. I'm currenlty using Arch, and  what should be done in the Arch case is to enable the service:
`sudo systemctl enable --now snapd.socket`

But I agree with you. I will try to improve this warnings in the next releases.

**Comment by vinifmor** [comment]
In **0.7.2** the message is changed by **started or enabled**.
