### ISSUE TITLE
Not listing installed packages for Flatpak 1.2.5

### ISSUE THREAD

**Issue by satourne** [vinifmor/bauh#201]
**After opening a new issue**
First of all : Thanks.
I open that issue as an information for your curiosity.
I know that the officials platforms are 
-     Ubuntu-based distros (20.04)
-     Arch-based distros

 
**Describe the bug**
$ flatpak --version
Flatpak 1.2.5
$ bauh --version
bauh 0.9.19

I have flatpak and when I launch bauh, I can see softwares those are available.
![screenshot-bauh](https://user-images.githubusercontent.com/612785/136538197-a005ed47-cfc6-4bde-a607-639c3797ee41.jpg)

But when I click on Installed, I see nothing in despite of I have flatpak
![screenshot-bauh-installed](https://user-images.githubusercontent.com/612785/136538230-e9cecae0-fdb6-4821-8d31-533c2eafc933.jpg)

**Software Environment**
**bauh version:** bauh 0.9.19
**O.S:** Debian GNU/Linux 10 (buster)
**Python version:** Python 2.7.16
                          Python 3.7.3
**Installation method:** pip

### Informations :

With Flatpak 1.2.5, the output is :
flatpak list -d
Description  Application     Version  Branch Arch   Origin  Installation Ref  Active commit Latest commit Installed size Options
PulseEffects - Effets… …m.pulseeffects 4.8.4    stable x86_64 flathub system       com.github.wwmm.pulseeffects/x86_64/stable         f2cf4f14601c  ?              43,6 MB       system,current

So I see there is a problem in gems/flatpak/flatpak.py
File "/usr/local/lib/python3.7/dist-packages/bauh/gems/flatpak/flatpak.py", line 1XX, in list_installed
    'arch': ref_split[1],
IndexError: list index out of range

I change some lines like this :

```
def list_installed(version: Version) -> List[dict]:

    apps = []
    if version < VERSION_1_3:
...
                runtime = 'runtime' in data[1]
...
                apps.append({
                    'id': data[8],
                    'name': data[1].split('.')[-1].capitalize(),
                    'ref': data[7],
                    'arch': data[4],
                    'branch': data[3],
                    'description': data[0],
                    'origin': data[5],
                    'runtime': runtime,
                    'installation': 'user' if 'user' in data[6] else 'system',
                    'version': data[2] if runtime else None
                })

...
```

and it works differently ...
![screenshot-bauh-modified](https://user-images.githubusercontent.com/612785/136540102-df1bac8a-460a-4a12-b353-6559521fbf6f.jpg)

Thanks again.

P.S: I'm a newbie with python...

**Comment by vinifmor** [comment]
Fixed on the **staging** branch: https://github.com/vinifmor/bauh/commit/a6c065efb658fcc78716c31f410a101b37258c6b
