### ISSUE TITLE
https://github.com/vinifmor/bauh/tree/readme/bauh/desktop : 404, does not exist

### ISSUE THREAD

**Issue by LinuxOpa** [vinifmor/bauh#205]
https://github.com/vinifmor/bauh/tree/readme/bauh/desktop : 404, does not exist

**Comment by vinifmor** [comment]
Thanks for reporting the outdated link. Fixed https://github.com/vinifmor/bauh/commit/6f65556c05ae272c1dbbd557c7f80a606658eb56
