### ISSUE TITLE
are the characters '?' in the update process intentional?

### ISSUE THREAD

**Issue by LinuxOpa** [vinifmor/bauh#211]
**update**
done

**Describe the bug**
are the characters '?' in the update process intentional?
see screenshot

**Software Environment**
bauh version: 
O.S: Ubuntu 20.04.3LTS LANG=de_DE.UTF-8
Python version: 3.8
Installation method: pip 

![bauh](https://user-images.githubusercontent.com/41851582/143677125-f54bc64a-2df7-430a-aa31-bc55d0aa93a7.jpg)

**Comment by vinifmor** [comment]
@LinuxOpa , bauh just prints the output of the back-end command. No treatment is applied.

**Comment by LinuxOpa** [comment]
ok, closed
