### ISSUE TITLE
[New AppImage] Logseq

### ISSUE THREAD

**Issue by senntore** [vinifmor/bauh#212]
- Application name: Logseq
- Github page: https://github.com/logseq/logseq
- Official website (if available): https://logseq.com

**Comment by vinifmor** [comment]
@senntore logseq has been added to the back-end script. It should be available in a few hours. Let me know if it is ok.

![bauh-logsec](https://user-images.githubusercontent.com/4312414/144102325-f7bb3d07-650e-44fc-842d-c2c8648b8193.png)

**Comment by senntore** [comment]
It works, thanks!
