### ISSUE TITLE
update of an already updated software

### ISSUE THREAD

**Issue by Fra1962** [vinifmor/bauh#214]
Hi,
I am using bauh with an other package manager ( pamac on manjaro ) ; if i update some AUR software with pamac before updating it with bauh, bauh does not detect that the package is already up to date (the version number is the same), and if i select "ignore updates" it  ignores all future software updates. Can you solve the problem?

**Comment by vinifmor** [comment]
Hello @Fra1962 , bauh uses it's own database when dealing with AUR packages. So if you update the package with a different tool, bauh's database gets out of sync. Updating the package again with bauh would solve your issue.

**Comment by Fra1962** [comment]
Sure, mine was just a tip to improve the software.Il 7 Dic 2021 19:52, Vinícius Moreira ***@***.***> ha scritto:
Hello @Fra1962 , bauh uses it's own database when dealing with AUR packages. So if you update the package with a different tool, bauh's database gets out of sync. Updating the package again with bauh would solve your issue.

**Comment by RoestVrijStaal** [comment]
@vinifmor It would be handy to mention in the README and behind the tooltips in the settings dialog that bauh uses its own database/index.
