### ISSUE TITLE
No Flatpak remotes set. It will not be possible to search for Flatpak apps.

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#22]
The snapd warning tells the user that they can disable snap in the Application types configuration.  The warning for flatpak doesnt say that flatpak can also be disabled in the Application types config.

One possible way to streamline this user experience is to show the Application types window if any type isnt working correctly, and include the warning text on that window.

**Comment by vinifmor** [comment]
It's a good suggestions. I will consider what you wrote here, and see the best way to add this behavior to the tool.

**Comment by vinifmor** [comment]
In **0.7.2**, bauh will let the user know that Flatpak can be disabled as well.

**Comment by vinifmor** [comment]
bauh **0.8.1** always adds the Flathub repo at the user level, so the warning was removed
