### ISSUE TITLE
How to reset Bauh password?

### ISSUE THREAD

**Issue by foundationer** [vinifmor/bauh#221]
Hi

This is more a question than an issue. I use **Bauh** in **Arch Linux**. I set a password for it but I forgot it.
I can't find a way to reset it. I don't mind having to reinstall all applications managed with Bauh, so I tried to remove the application and install it again, but it still asks me for the password.
Is there a way to reset it?

Thanks in advance.

**Comment by vinifmor** [comment]
Hi @foundationer , actually bauh does not have/store a password. It only requests the root password when a given action requires it.

**Comment by foundationer** [comment]
That explains a lot :)
I can access now. Thanks for your help.
