### ISSUE TITLE
Unable to enable appimage support

### ISSUE THREAD

**Issue by AMoonRabbit** [vinifmor/bauh#228]
**Before opening a new issue**
Install the **staging** branch and check if the unexpected behavior is happening there as well.
If you are on ArchLinux-based distro, you can install it through AUR (**bauh-staging**). Otherwise, you have
to clone the repository and install it with pip:
```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh  # or venv/bin/bauh-tray
```
 
**Describe the bug**
When going into the 'Types' tab of 'Settings', AppImage, among other types, are not available. Only Faltpak is available to be managed, enabled, or disabled.

**Software Environment**
bauh version: 0.9.26
O.S: Pop_OS 21.10
Python version: 3.9.7
Installation method: pip

P.S: these instructions and the template must be respected, otherwise your issue will be closed.

![image](https://user-images.githubusercontent.com/3766988/152680434-43504eea-66f1-42da-be6b-40fe263aad97.png)

**Comment by vinifmor** [comment]
If you hover the mouse over the red "?" icons, they will give you a hint about what is missing on your system. You can also check on the README.md file about the required dependencies for each supported type.
