### ISSUE TITLE
Snap apps disappear when changing styles

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#23]
When I switch from Style: Fusion to Style: gtk2 or Windows, the snaps would disappear after the restart.
Switching again to Style: Fusion and the snap apps appear again.

It feels like something is wrong with the restart logic.

My process tree would look like
```
31479 pts/0    Sl     0:03 /usr/bin/python3 /usr/bin/bauh
31515 pts/0    S      0:00  \_ /usr/bin/python3 /usr/bin/bauh
31552 pts/0    Z      0:00  \_ [snap] <defunct>
```

Sometimes only two of the snaps would appear in the list.

When the snaps disappear, the gtk2 and Windows style windows did not include the Type: selector, probably because I then only had one type remaining: AppImage.

**Comment by vinifmor** [comment]
I believe this happened because the Ubuntu API probably blocked the query requests. It happens sometimes, but I will try to reproduce here.
