### ISSUE TITLE
bauh in conatiner not displaying or searching local or repo packages, only installed flatpaks

### ISSUE THREAD

**Issue by durapensa** [vinifmor/bauh#232]
Running bauh in a [Distrobox](/89luca89/distrobox/) container, it's not displaying  or searching local or repo packages, only installed flatpaks. Nothing unusual appeared in `bauh --logs`; there's probably a simple fix for this, but I don't know where to look.

**Software Environment**
bauh version: 0.9.28 (in container)
Host OS: Fedora Silverblue 35
Container OS: Fedora 35, also tested with Debian 11.2, with only change to default packaging in both containers an added Flatpak remote for Flathub 
Python version: 3.10.10 (in container)
Installation method: `pip install bauh` (in container)

**Comment by vinifmor** [comment]
@durapensa this is expected. bauh currently is not able to manage Debian/Fedora packages You can have a look at the currently supported packaging types [here](https://github.com/vinifmor/bauh#types)

**Comment by durapensa** [comment]
Should it list list remote flatpaks, i.e. what you'd get from `flatpak remote-ls flathub`?

**Comment by durapensa** [comment]
Yes, I'm unable to find packages from remotes configured (just one system remote, for flathub), either through search or a listing. I'm unsure where to look to troubleshoot.

**Comment by vinifmor** [comment]
Could you launch bauh with logging and paste the output here after performing a search (`bauh --logs`) ?
