### ISSUE TITLE
Massive amounts of DNS Lookups

### ISSUE THREAD

**Issue by Tylexon** [vinifmor/bauh#234]
I use pihole to monitor my DNS look up and block things, I have seen a massive increase of lookups to flatpak.org and it only happens when bauh is started in the tray.
When I say massive amounts I mean 2400 lookups for flatpak.org in a space of 5minutes, maybe it's normal expected behavour ?

Using version bauh 0.9.28
only flatpak is enabled
Distro is Pop!_OS 21.10 x86_64
Desktop Gnome 40.5
Kernel 5.15.23

If anymore information is needed I can provide more.

**Comment by vinifmor** [comment]
Hi @Tylexon. The number of calls are related to the update checking interval that can be changed through the settings window or the directly on the file (default to 30 seconds). But it seems the Flatpak code may be performing some unneeded calls on the tray mode. Thanks for reporting.

**Comment by vinifmor** [comment]
Duplicate calls have been removed and now the default update checking interval is 30 minutes. These changes have been published to the **staging** branch.
