### ISSUE TITLE
Delete previous backups after making a new one

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#240]
It would be great if I could be asked to delete previous (I'm using incremental) backups made by bauh after making a new bauh backup.

I'm using Linux Mint and it doesn't delete manually made backups, so I have to manually delete those made by bauh once in a while. It gets annoying, especially once I'm pretty much out of space and need to do other things, but I have to sit and watch those being deleted. If I could delete previous bauh backups after making a new one, it wouldn't get to that point.

Maybe the "Comment" part of backups could be used to identify bauh backups?

PS: I don't know how to make Suggestions - when I try to make a new Issue, I have a choice between a bug report and an AppImage thingy. :(

**Comment by vinifmor** [comment]
Hello @Templayer , it already supports that feature. Just changes the backup mode to "Single"

**Comment by Templayer** [comment]
> Hello @Templayer , it already supports that feature. Just changes the backup mode to "Single"

Oh, sorry, I didn't realize it worked that way.
