### ISSUE TITLE
Individual options in Settings are too far away vertically

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#241]
**Describe the bug**
When using the Fusion theme (haven't tried the others):

![image](https://user-images.githubusercontent.com/11728067/158355199-d5e5075c-209f-4e53-b325-ce9b14b9042a.png)

**Software Environment**
bauh version: 0.10.0
O.S: Linux Mint 20.3 Una with Cinnamon; kernel: 5.4.0-104-generic
Python version: Python 3.8.10 + Python 2.7.18 (I would assume it uses the first one, because of pip3)
Installation method: pip3 (it would be great if the bauh Help dialog would also say if it is under pip, AppImage, etc. )

**Comment by vinifmor** [comment]
Fixed on the staging branch
