### ISSUE TITLE
Seems like bauh has problem a with Unicode

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#242]
**Describe the bug**
I can't currently post an image, but when I do actually update applications through bauh, the progress bar in the details view shows question marks. I presume that is a bug and it is supposed to have some Unicode symbols for depicting it, and that it isn't a feature. Because using question marks for a progress bar would be silly. :P

I'll try getting a picture next time I actually get to download an actual update.

This *might* be connected to issue https://github.com/vinifmor/bauh/issues/238

**Software Environment**
bauh version: 0.10.0
O.S: Linux Mint 20.3 Una with Cinnamon; kernel: 5.4.0-104-generic
Python version: Python 3.8.10
Installation method: pip3
System/input/layout language: Czech (might be important for this issue)

**Comment by Templayer** [comment]
> @Templayer , what's your system encoding ?

I would presume UTF-8, but how do I check that? I tried googling, but couldn't get a proper answer...

**Comment by Templayer** [comment]
Do I need to use @vinifmor if I'm using Reply/Quote? I'm not sure if I should or not. Well, this comment solves that if it is indeed needed.

There is some interesting info about that and python here: https://askubuntu.com/questions/3248/what-is-the-default-character-encoding

Terminal language/encoding:
![image](https://user-images.githubusercontent.com/11728067/158539652-b2b308f8-da1b-4568-8358-5b7c674de60a.png)

System language:
![image](https://user-images.githubusercontent.com/11728067/158542010-174eb09b-7a35-49b9-94ee-c5f575e139dd.png)
![image](https://user-images.githubusercontent.com/11728067/158542059-73ce0b59-05cc-40e4-9087-a8b403832013.png)

**Comment by vinifmor** [comment]
I'm going to have a look if it is possible to change the encoding of the component responsible to display the action details. Thanks for pointing that out.

**Comment by Templayer** [comment]
Nope, found it - look at the description for Web GNOME!

![image](https://user-images.githubusercontent.com/11728067/159892554-e0c3a1e6-ac02-4cc2-9947-ff9bd91b8bd4.png)

**Comment by vinifmor** [comment]
This issue seems to be on the Flatpak side. I've been testing some scenarios. I haven't come across such issue with the other back-ends.

**Comment by Templayer** [comment]
@vinifmor That does seem to be the correct conclusion.

Look at the selected row:

![image](https://user-images.githubusercontent.com/11728067/159938680-a4ac2ba4-eac5-4fda-848b-12e2817891ba.png)

Except for the log section where I think it also screws up for non-flatpacks. I think it does for snaps too, and I haven't yet really checked the debians.

**Comment by vinifmor** [comment]
I believe it is fixed for Flatpak (I'm going to perform more testing over the other types). Could you give me a feedback ? Just download the compressed fix from this branch https://github.com/vinifmor/bauh/archive/55aaaebf2e25145912dd6df3bf1e49b43228ba95.tar.gz and install with pip (`pip install [path_to_file]`)

**Comment by Templayer** [comment]
Just as a note: I've used pip3.

![image](https://user-images.githubusercontent.com/11728067/160079396-cafb2977-f113-4b41-b799-38adec6b3010.png)

Excellent job! Seems to be working! :)

The list now lists Unicode symbols correctly for diacritical symbols for flatpacks as well:

![image](https://user-images.githubusercontent.com/11728067/160081740-4a97899c-0e69-4f36-9a04-ea19bfbb46d1.png)

Feel free to close the issue when the new version is released. ^_^

**Comment by vinifmor** [comment]
Good news then. I will still have a look on the other types before closing the issue. Thanks for the feedback.

**Comment by Templayer** [comment]
No problem. Let's make this software as good as it can be.
