### ISSUE TITLE
interface not rendering

### ISSUE THREAD

**Issue by connected201** [vinifmor/bauh#248]
hi, i tried to run bauh on slax (https://slax.org)
and i receive this:
![image](https://user-images.githubusercontent.com/20506433/160442486-37f49110-4274-4a0e-b78f-c726e3a0ee26.png)

all dependencies (sudo apt-get install python3 python3-pip python3-yaml python3-dateutil python3-pyqt5 python3-packaging python3-requests) was installed successfully

**Comment by vinifmor** [comment]
Did you install pip ? Have you tried the AppImage ?
