### ISSUE TITLE
[bug] Some GUI components do not properly adjust the text size

### ISSUE THREAD

**Issue by BlitDev** [vinifmor/bauh#253]
My version: 0.10.1
My OS: Arch Linux

When using some languages, the text does not fit into the button, so it would be nice to have language change support in the program.

**Comment by vinifmor** [comment]
Could you attach a picture of the scenario you described ?

**Comment by BlitGaming** [comment]
> Could you attach a picture of the scenario you described ?
![1g](https://user-images.githubusercontent.com/79034202/162342308-97f297d1-e44d-47e8-8d75-5d8e30394935.png)

**Comment by vinifmor** [comment]
It seems squeezed indeed. Thank you for sharing this issue.

**Comment by vinifmor** [comment]
Fixed on the **staging** branch. Since you are on Arch, you can install the package **bauh-staging** from AUR.
