### ISSUE TITLE
[bug] Uninstall logs are not available

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#255]
A minor nitpick - when uninstalling a Debian app (copyq in my case) the info pane ended up on the following line:

"Updating the apps index ..."

.... and that's it. It seems like it has finished, but there isn't proper feedback there towards the user. The icons for installing and uninstalling did change, but it took me a while to find out.

A very simple and straightforward solution would be to write down "The uninstallation has been completed!" when the process is finished for app types that do not state that information out of the gate. Like Debian, seemingly.

A similar nitpick might be found for installations and other actions as well, so some testing might be in order.

If I could add Labels, I would add "User Experience" to this Issue. :P

**Comment by Templayer** [comment]
Installing the same application ends up like this:

> Updating the apps index...
> Installation logs can be found at "/tmp/bauh@jboksa1/logs/install/debian/copyq/1649402102.log"

So there "kinda" is a confirmation that it has been finished - why doesn't uninstallation produce logs as well? Stuff can f*ck up there too. :)

**Comment by vinifmor** [comment]
The uninstall logs are not being written indeed. Thank for reporting.

**Comment by Templayer** [comment]
Yup. What a random find, huh?
