### ISSUE TITLE
/snap/bin was not found in your $PATH

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#26]
After installing a snap app, I get the following warning in the console.

> Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more details.

That probably should have been done by some part of the snap install, however it is something that maybe bauh can help users do.  https://pypi.org/project/userpath/ is a nice tool for adding items to the user scripts to add entries to `PATH`.

**Comment by vinifmor** [comment]
Hi @jayvdb, I have never got this warning. What distro are you currently using ? I will try to mimic the behavior and see how bauh can suggest a solution for the user.

**Comment by jayvdb** [comment]
I am using openSUSE.

**Comment by vinifmor** [comment]
This issue was already fixed on the latest releases. https://github.com/vinifmor/bauh/blob/master/bauh/gems/snap/snap.py#L16

The "print_error=False" skips this warning...
