### ISSUE TITLE
Conflicting package removal force removes dependent packages when it should not

### ISSUE THREAD

**Issue by polarathene** [vinifmor/bauh#268]
**Describe the bug**

This is probably a settings issue but it is unclear which one when I looked through them. I did not experience this with Pamac or `yay`. 

Installing a package such as `kwinft` to replace the installed `kwin` package finishes installation by requesting to uninstall the `kwin` package that it conflicts with (but also provides itself as `kwin`). Acknowledging the uninstall then requests to uninstall many system packages that depend on `kwin`, even though the new package provides `kwin` for them and is fine with other package managers.

![Screenshot_20220506_200844](https://user-images.githubusercontent.com/5098581/167226099-1c9ab599-93a0-4b6d-8996-f19184e78607.png)

The checkboxes do not respond to any clicks to opt-out and keep that package. A user that goes ahead with this will have an broken system afterwards. Re-installing the packages can partially restore what the user had, though in my experience (_I did this via VM so I had a snapshot to revert back to_) this lost some settings (_at least for SDDM with theme and autologin)_.

**Software Environment**
bauh version: 10.3 (staging)
O.S: EndeavourOS - Latest updates (as of May 2022)
Python version: 3.10.4
Installation method: pacman/yay

**Comment by vinifmor** [comment]
I will have a look into this. Thanks for reporting.

**Comment by vinifmor** [comment]
I will have a look into this. Thanks for reporting.

**Comment by vinifmor** [comment]
I've pushed some fixes to the staging branch. Based on the scenarios I've tested, it is working fine. Let me know if you face this sort of issue again.
