### ISSUE TITLE
Application types window Exit button

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#27]
Throughout the app there are no Close or Exit window buttons, except on the Application types window, and it uses "Exit" instead of the more usual "Close".  The button doesnt exit the app, which is what "Exit" buttons usually do.

**Comment by vinifmor** [comment]
Hi @jayvdb , you are right. I will change the label to "Close" in the next releases.

**Comment by vinifmor** [comment]
Changed to "Close" in **0.7.2**
