### ISSUE TITLE
Installation of .AppImage fails thanks to wget SSL cert problem

### ISSUE THREAD

**Issue by MANICX100** [vinifmor/bauh#270]
For example if trying to install poddr
```
--2022-05-18 22:41:39--  https://github.com/Sn8z/Poddr/releases/download/2.0.0/Poddr-2.0.0.AppImage
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
ERROR: cannot verify github.com's certificate, issued by 'CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1,O=DigiCert Inc,C=US':
Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
rm -rf /tmp/bauh@dkendall/appimage/download/Poddr-2.0.0.AppImage


* The operation logs can be found at "/tmp/bauh@dkendall/logs/install/AppImage/Poddr/1652910099.log"
```
 
**Describe the bug**
wget throws a certificate error so all appimage downloads fail.

**Software Environment**
bauh version:  0.10.2
O.S: name and version  Fedora 36
Python version: 3.10.4.5
Installation method: .AppImage

P.S: these instructions and the template must be respected, otherwise your issue will be closed.

**Comment by MANICX100** [comment]
I also have been unable to add --no-check-certificate. (I accept this is a security risk)

I tried adding it to my ~/.wgetrc which works in general system usage but not inside bauh.

**Comment by vinifmor** [comment]
This problem wouldn't happen with every file and could be a security issue as you mentioned. But I can add an optional configuration property on the settings window to bypass certificate issues.

**Comment by vinifmor** [comment]
Already available on the staging branch

**Comment by vinifmor** [comment]
![check_ssl](https://user-images.githubusercontent.com/4312414/169398704-66911d25-ce94-474a-92bb-d807d81b634e.png)
