### ISSUE TITLE
Installed update wont dissapear

### ISSUE THREAD

**Issue by MANICX100** [vinifmor/bauh#273]
**Describe the bug**
The following update IS installed
![image](https://user-images.githubusercontent.com/5303241/170564928-974ebc56-910a-4923-a9fc-0e44eca1461e.png)
It always appears on loading bauh, when I press update and show details it skips as its already installed then runs fstrim and asks me to reboot my PC.

**Software Environment**
bauh version: 0.10.2
O.S: name and version Fedora 36 
Python version: 3.10.4
Installation method: .AppImage

**Comment by vinifmor** [comment]
Hello @MANICX100 , try the staging branch. There are Flatpak fixes published there related to these locale updates

**Comment by MANICX100** [comment]
> Hello @MANICX100 , try the staging branch. There are Flatpak fixes published there related to these locale updates

To do so do I have to build from source? Or are there .appimage / pip repos I can use?

**Comment by MANICX100** [comment]
Edit:

`python -m pip install git+https://github.com/vinifmor/bauh@staging`

worked for installing staging.

However, the problem remains.

**Comment by MANICX100** [comment]
The solution was to run

`flatpak uninstall --unused`

**Comment by vinifmor** [comment]
Ok. Since you already solved by uninstalling the locale, we will not able to investigate the cause.
