### ISSUE TITLE
[New AppImage] Bitwarden

### ISSUE THREAD

**Issue by Lennox84** [vinifmor/bauh#278]
- Application name: Bitwarden
- Github page: https://github.com/bitwarden/clients/releases
- Official website (if available): https://bitwarden.com/

**Comment by vinifmor** [comment]
The Desktop release is still in beta (https://github.com/bitwarden/clients/releases/tag/desktop-v2022.5.0). It will automatically be added to the database when final release is available.

**Comment by Lennox84** [comment]
Amazing. Thank you.
