### ISSUE TITLE
slack has License: unset

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#28]
The slack snap app shows "License: unset", which may mean it is literally text "unset" (not likely), but probably means there is no stated license, and the lack of a license probably means Proprietary.  A blank value is probably better.

**Comment by vinifmor** [comment]
Hi @jayvdb , it a good suggestion. I will add to the backlog.

**Comment by vinifmor** [comment]
If the license is set as **unset**, bauh will not display anymore in **0.7.2** ( just released ).
