### ISSUE TITLE
[appimage] Security certificate check fails when installing AppImages

### ISSUE THREAD

**Issue by Lennox84** [vinifmor/bauh#280]
**Before opening a new issue**
Install the **staging** branch and check if the unexpected behavior is happening there as well.
If you are on ArchLinux-based distro, you can install it through AUR (**bauh-staging**). Otherwise, you have
to clone the repository and install it with pip:
```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh  # or venv/bin/bauh-tray
```
Appimage (i.e. Superslicer) installs correctly using the above pip install

**Describe the bug**
But when using the bauh.appimage I get this error (see attached image)

**Software Environment**
bauh version: 0.10.3
O.S: Feddora 36 (KDE Spin)
Python version: 3.10.4
Installation method: Appimage

![bauh appimage](https://user-images.githubusercontent.com/8501560/172269766-183a26e1-0b6e-40db-877b-66d93155d44a.png)

P.S: these instructions and the template must be respected, otherwise your issue will be closed.

**Comment by vinifmor** [comment]
It is happening only with the AppImage distribution (I'm going to investigate the cause here, but it is probably related to attach wget within the AppImage). 

For now you can disable the "Check security certificate" on "Advanced" settings, or try a different supported downloader tool (aria or axel).

**Comment by vinifmor** [comment]
Fixed on the staging branch... it will be available on the AppImage release

**Comment by Lennox84** [comment]
Hello again... It's back... I'm OpenSUSE now and this game problem has come up in both the appimage install and the Isolated install? Do we re-open this issue or should I create a new entry?

**Comment by Lennox84** [comment]
Disabling Security check works. 
Using Aria2 with the bauh Appimage and security check on works.
So could we set aria2 as the default downloader maybe? It has always worked well for me, but not sure if it's an option to become default?

**Comment by vinifmor** [comment]
I'm gonna reopen it then. Could you attach logs from bauh's wget call ?

**Comment by vinifmor** [comment]
`wget` has been replaced by a python implementation on  `0.10.6`
