### ISSUE TITLE
ChromeOS & Bauh's password requirement

### ISSUE THREAD

**Issue by boognish-rising** [vinifmor/bauh#285]
I don't know that I'd call this a bug and therefore used a blank template rather than a bug report template, but it's something that is definitely standing in between me and the ability to use Bauh, at least on my Pixelbook running ChromeOS. Obviously I have a Linux environment established and running and it took jumping through several hoops but I was able to get bauh installed and after several seemingly stalled launches, I was able to get into the program itself and configure it. I didn't have the foresight to disable the password request and since ChromeOS' Linux environment is password-less (not at all my preference but not my call), Bauh's request for one puts me in a bit of an awkward spot. I tried running bauh --settings and changing the requirement from CLI and I thought that would be that, but at next launch a password was still required. Then I remembered that I thought I had briefly seen something about settings taking effect after a restart after saving my configuration changes before hastily dismissing it so I restarted my Pixelbook however, still at launch Bauh insisted upon me providing a password. Running bauh --settings again confirmed that the changes were not persisting. "Okay so I'll just nuke my setup since I only put 5 or 10 minutes into my original configuration changes anyway," I thought and with that I ran bauh --reset thinking that that would be the end of it for sure, as the very first time I ran the program there was no such request for a password and I was actually in and had I known that that was to be my only access, I might have taken better advantage of it, but at this point I was under the impression that I could get back to that first run state. However again after running the reset command, no luck. Same was the case after a power cycle. 

At this point I almost gave up and/or headed in this direction to submit an issue but I figured I would try some Google-Fu maneuvers and see if I could make any headway before bugging you guys here. I found # # something that stated that if for whatever reason, you were to be requested for a password by any Linux application in the Chrome OS Linux environment /container that it would very likely be test0000 however, bauh was not approving of this (regardless of case). 

I know that you can configure a sudo password if you really wanted to, which I probably should have done, but I only use the Crostini Linux container functionality baked into ChromeOS, not a full-fledged Linux distro with desktop environment alongside Chrome OS. As such, I didn't think that setting a root password on a device that doesn't require its use (or even provide the option to do so) would be it all necessary. I should've known that I'd push the boundaries of the Linux "container" layer and played it safe but I didn't and here I am. I'm sure the fix is a straightforward enough solution but I'm not super well versed on Linux as run from ChromeOS devices yet and it regularly laughs at my attempts at using Linux(proper) fixes.

Any help would be greatly appreciated!

If it's at all relevant, as I alluded to the device in question is a Pixelbook (not Pixelbook Go), i7 processor 512GB variant (so not ARM based). ChromeOS is current and is on the stable channel. Developer mode is enabled on it as well.

Thanks!

Edited to add that I did try bauh-staging as well, same result(s)

**Comment by boognish-rising** [comment]
Ok, I'm going to mark This as closed already, as a bit more Google searching ultimately saved the day. 

For anyone that might stumble across this down the line, the solution actually was staring me in the face, as I specifically mentioned that Linux on ChromeOS is password-less, including for sudo/su, which is all I should've needed to know:

run:
```
sudo su 
passwd **USERNAME**

```
(make sure you substitute your Linux username for USERNAME in the passwd command. It should be the same as your ChromeOS PW but it's whatever comes before ```@penguin:~$``` in the command line interface)

DONE. 

wipe your hands of that annoyance and carry on.

**Comment by vinifmor** [comment]
Hi @boognish-rising, I'm glad bauh has been useful for you and you were able to figure out the issue
