### ISSUE TITLE
Unable to activate Web application type even if bs4 and lxml are installed with pipx

### ISSUE THREAD

**Issue by matbgn** [vinifmor/bauh#286]
**Describe the bug**
I'm not able to activate the checkbox for web application type even if dependencies are satisfied. Still getting the "python3-beautifulsoup4 
is not installed" message.

Unlike AppImage and Flatpak which worked like a charm after sqlite3 and flatpak package installation. ;-)

**Software Environment**
bauh version: 0.10.3
O.S: Ubuntu Jammy Jellyfish 22.04 LTS
Python version: 3.10.4
Installation method: pipx

**Comment by vinifmor** [comment]
Hi @matbgn , have you restarted bauh after installing these dependencies ? Since they are Python dependencies and bauh is a Python application, you would need to restart it.

**Comment by matbgn** [comment]
Hi,

Course I had and the machine also with no better results.

Any other idea or log retrieve way?

**Comment by vinifmor** [comment]
Try opening a Python shell through a CLI (`python 3`) and execute the following command: `from bs4 import BeautifulSoup, SoupStrainer`. If an exception is raised, it means something is wrong with the installed `beautifulsoup4`. If that is the case, you could check if the package is named differently for your Linux distribution.

**Comment by matbgn** [comment]
There is no problem with bs4:

![image](https://user-images.githubusercontent.com/13169819/183567846-6cc9d70f-1714-44a0-ba40-7fb9bad9d27b.png)

![image](https://user-images.githubusercontent.com/13169819/183567937-f1b1016c-c30c-422e-8892-3789a849489a.png)

**Comment by vinifmor** [comment]
I believe it might be something related to the  `pipx` environment. Try installing [beautifulsoup4](https://pypi.org/project/beautifulsoup4/) and [lxml](https://pypi.org/project/lxml/) with it as well.

**Comment by matbgn** [comment]
Tried it but I really think that the packaging/linking has to be done at bauh level:

```
$ pipx install beautifulsoup4

No apps associated with package beautifulsoup4 or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

As it is already installed on shared environment:
```
$ pip3 install beautifulsoup4
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bs4 in /home/matbgn/.local/lib/python3.10/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4) (4.10.0)
```

**Comment by vinifmor** [comment]
You could try using the raw virtualenv library (as described on the [README.md](https://github.com/vinifmor/bauh#inst_iso))

**Comment by matbgn** [comment]
I typically want to install bauh as a "standalone" app so makes less sense to stick on venv and therefore multiple operations.

**Comment by vinifmor** [comment]
Have you tried the [AppImage](https://github.com/vinifmor/bauh/releases/download/0.10.3/bauh-0.10.3-x86_64.AppImage) release ? It has a self-install option to enable self-management (also it generates the desktop entry)

**Comment by matbgn** [comment]
I will thanks

**Comment by matbgn** [comment]
It installs perfectly with the corresponding option, but I'm surely missing something, as the image is not configured right away. Any advice?

**Comment by vinifmor** [comment]
Sorry, when you say is not configured, you mean not displayed for managing on bauh itself ?

**Comment by matbgn** [comment]
Yep - sorry for my english BTW - I mean that the icon is not set up so the application manager on my Ubuntu 22.04 machine could not display it.

**Comment by matbgn** [comment]
I finally achieved to install bauh within pipx and therefore augment my mastery of pipx. It's simple as running the following commands:

```
pipx inject bauh bs4
pipx inject bauh lxml
```

Therefore, the overall process that would have place in the docs could simply be:
```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
pipx install bauh
pipx inject bauh bs4
pipx inject bauh lxml
```

Many thanks for your support along the path!
