### ISSUE TITLE
Update notification doesn't reflect all pending updates on first boot

### ISSUE THREAD

**Issue by T3HM3T4L** [vinifmor/bauh#296]
Most times when I boot there will either be no notification (there's nothing to update) or a "1 available update" notification, about a flatpak that updates very regularly.
When I open up Bauh, it'll show there are many more packages to update, besides the 1 flatpak update it notified me of.
If I restart Bauh without upgrading anything, the notification will correctly display (current example before me)

"26 available updates
* Arch - Repository (25)
* Flatpak (1)"

**Software Environment**
bauh version: 0.10.3
O.S: Operating System:
EndeavourOS
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Python version: Python 3.10.7
Installation method: yay AUR

I have added Bauh-tray to my autostart programs, if that should make a difference.

**Comment by vinifmor** [comment]
Hi @T3HM3T4L , this behaviour is expected since the `bauh-tray` does not run as a root user and cannot synchronize the Arch database before the management panel is opened.
