### ISSUE TITLE
Failure to install debian packages (probably just the i386 thingie)

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#298]
**Describe the bug**
Debian packages are not installed:

![image](https://user-images.githubusercontent.com/11728067/196637689-949d966f-cae9-482f-85b0-663725c791fa.png)

(also, the Upgrade Summary doesn't enlarge the list if the window is enlarged)

![image](https://user-images.githubusercontent.com/11728067/196637911-7129155d-15d0-4315-b818-5574de8597a8.png)

The "i386" package isn't a package. I have enabled i386 due to a Wine tutorial. https://wiki.winehq.org/Ubuntu

```
sudo -S --preserve-env=DEBIAN_FRONTEND aptitude upgrade -q -y --no-gui --full-resolver i386 libpulse-mainloop-glib0 libpulse0 libpulsedsp pulseaudio pulseaudio-module-bluetooth pulseaudio-utils sudo -o Aptitude::ProblemResolver::RemoveScore=9999999 -o Aptitude::ProblemResolver::EssentialRemoveScore=9999999 -o Aptitude::Delete-Unused=false

Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
Unable to apply some actions, aborting
Couldn't find any package whose name is "i386", but there are 344 packages which contain "i386" in their name:
(too many to show, the limit is 40)
```

Deselecting libpulse0:i386 doesn't make that package disappear from the list of packages to be installed in the summary, and I cannot deselect i386 in the summary, so I'm effectively stuck.

It is interesting to note that those updates do not show up in the apt/deb Mint manager (except for Firefox which seems to be currently just getting caught in the printscreening crossfire, getting to a wrong place at a wrong time)

![image](https://user-images.githubusercontent.com/11728067/196640401-02606a0a-b2bd-46f2-91bb-3574ff87dd73.png)

**Software Environment**
bauh version: 0.10.3 Staging by running:

```
sudo rm -rf /home/jboksa1/bauh
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install wheel
venv/bin/pip install beautifulsoup4
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh
```

O.S name and version: Linux Mint 21
Python version: 3 :P
Installation method: pip

**Comment by Templayer** [comment]
Fun fact: Webmin IS capable of proceeding with such an update:

![image](https://user-images.githubusercontent.com/11728067/196693042-697b64bf-2c7b-4bbc-8b82-334cc07004a2.png)

![image](https://user-images.githubusercontent.com/11728067/196693190-2293fd5a-d0f4-411a-b438-e9ed0e00c831.png)

**Comment by Draguljche** [comment]
For me it also Uninstall some packages which are not to be uninstalled, when I try it with Plasma Discover it Ugrade well. Good thing I have setup Timeshift+Grub-Btrfs Snapshots. BTW Im using Debian(SpiralLinux) Sid.

**Comment by Templayer** [comment]
> For me it also Uninstall some packages which are not to be uninstalled, when I try it with Plasma Discover it Ugrade well. Good thing I have setup Timeshift+Grub-Btrfs Snapshots. BTW Im using Debian(SpiralLinux) Sid.

That sounds like a different bug. Do you have printscreens, update logs, or anything to go from?

**Comment by vinifmor** [comment]
@Draguljche , this sounds like a different bug as @Templayer mentioned. Could you, please, open a different issue report and add more information ? (like: the packages you selected to upgrade and their versions, and what packages were displayed on the upgrade summary)

**Comment by Templayer** [comment]
Some more info about why I have my issue in the first place (enabled i386): https://askubuntu.com/questions/135463/why-is-wine-installed-automatically-with-i386-and-amd64-versions-in-12-04

**Comment by Draguljche** [comment]
> @Draguljche , this sounds like a different bug as @Templayer mentioned. Could you, please, open a different issue report and add more information ? (like: the packages you selected to upgrade and their versions, and what packages were displayed on the upgrade summary)

It happens when some packages where keept back, in this case ghostscript. It conflicts with postscript-viewer. When I run sudo apt nala upgrade it skips keept packages, I think Bauh need to skip those packages as well not because of that upgradable packages cannot be upgraded. Thats my suspicion. Plasma-Discover works like that as NALA frontend for APT. That happened before with some different packages which are keept back by Debian, as I mentioned before I use Sid for newer packages. I installed Bauh because it has Web Applications installer and AppImage to which Plasma-Discover doesnt have. So it would be great if that with Bauh not skipping automaticaly, keept packages, be integrated as feature. Muon Package Manager works that way with keept packages to.

**Comment by Templayer** [comment]
> > @Draguljche , this sounds like a different bug as @Templayer mentioned. Could you, please, open a different issue report and add more information ? (like: the packages you selected to upgrade and their versions, and what packages were displayed on the upgrade summary)
> 
> It happens when some packages where keept back, in this case ghostscript. It conflicts with postscript-viewer. When I run sudo apt nala upgrade it skips keept packages, I think Bauh need to skip those packages as well not because of that upgradable packages cannot be upgraded. Thats my suspicion. Plasma-Discover works like that as NALA frontend for APT. That happened before with some different packages which are keept back by Debian, as I mentioned before I use Sid for newer packages. I installed Bauh because it has Web Applications installer and AppImage to which Plasma-Discover doesnt have. So it would be great if that with Bauh not skipping automaticaly, keept packages, be integrated as feature. Muon Package Manager works that way with keept packages to.
> 
> EDIT: Btw, I upgrade system wide when it give me notifications that there are Upgrades...

... and why did you write this to this Issue instead of making a new Issue? This seems not to be connected to the i386 problem. Do you have problems with i386 architecture-based packages as well?

**Comment by Draguljche** [comment]
> > > @Draguljche , this sounds like a different bug as @Templayer mentioned. Could you, please, open a different issue report and add more information ? (like: the packages you selected to upgrade and their versions, and what packages were displayed on the upgrade summary)
> > 
> > 
> > It happens when some packages where keept back, in this case ghostscript. It conflicts with postscript-viewer. When I run sudo apt nala upgrade it skips keept packages, I think Bauh need to skip those packages as well not because of that upgradable packages cannot be upgraded. Thats my suspicion. Plasma-Discover works like that as NALA frontend for APT. That happened before with some different packages which are keept back by Debian, as I mentioned before I use Sid for newer packages. I installed Bauh because it has Web Applications installer and AppImage to which Plasma-Discover doesnt have. So it would be great if that with Bauh not skipping automaticaly, keept packages, be integrated as feature. Muon Package Manager works that way with keept packages to.
> > EDIT: Btw, I upgrade system wide when it give me notifications that there are Upgrades...
> 
> ... and why did you write this to this Issue instead of making a new Issue? This seems not to be connected to the i386 problem. Do you have problems with i386 architecture-based packages as well?

because its forcing on install i386 packages when something like that happens, when attempting upgrade.

**Comment by Templayer** [comment]
> because its forcing on install i386 packages when something like that happens, when attempting upgrade.

You didn't tell us that before. :)

**Comment by Draguljche** [comment]
> > because its forcing on install i386 packages when something like that happens, when attempting upgrade.
> 
> You didn't tell us that before. :)

Well I forgot to mention that  :)

**Comment by Templayer** [comment]
Possible partial solution (more of a workaround) - three new Debian options:

* Disable i386 packages (default)
* Enable i386 packages
* Enable i386 packages only for specific packages (with a list of strings for package names)

I would only enable those for my Wine packages. 

@Draguljche Would that solve your problem as well? At least as a workaround?

**Comment by Draguljche** [comment]
> Possible partial solution (more of a workaround) - three new Debian options:
> 
>     * Disable i386 packages (default)
> 
>     * Enable i386 packages
> 
>     * Enable i386 packages only for specific packages (with a list of strings for package names)
> 
> 
> I would only enable those for my Wine packages. This would also filter them for upgrade detection.
> 
> @Draguljche Would that solve your problem as well? At least as a workaround?

Ill try when Updates come. But if its not solve Ill use Plasma-Discover to upgrade my system to not broke something till its fixed in future versions of Bauh... As I said never had a problem on KDE Plasma with Discover. I wanted to use only Bauh as tool for installing/upgrade. It seems that for now its not possible.

**Comment by Templayer** [comment]
> > Possible partial solution (more of a workaround) - three new Debian options:
> > ```
> > * Disable i386 packages (default)
> > 
> > * Enable i386 packages
> > 
> > * Enable i386 packages only for specific packages (with a list of strings for package names)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would only enable those for my Wine packages. This would also filter them for upgrade detection.
> > @Draguljche Would that solve your problem as well? At least as a workaround?
> 
> Ill try when Updates come. But if its not solve Ill use Plasma-Discover to upgrade my system to not broke something till its fixed in future versions of Bauh... As I said never had a problem on KDE Plasma with Discover. I wanted to use only Bauh as tool for installing/upgrade. It seems that for now its not possible.

* *sigh* *

You read what I wrote wrong. What I am giving you are hypothetical options inside BAUH itself. I'm asking IF bauh had these options, WOULD it help in you case?

**Comment by Templayer** [comment]
> > Enable i386 packages only for specific packages (with a list of strings for package names)
> 
> No, I dont have those options inside Bauh Settings.

V

> I'm asking IF bauh had these options, WOULD it help in you case?

I'm giving up. Please learn basic English. For me, it's my third language, i.e. that's not a viable excuse.

**Comment by vinifmor** [comment]
folks, I've published a fix on the staging branch. Let me know if the issue has gone on your ends.

**Comment by Templayer** [comment]
> folks, I've published a fix on the staging branch. Let me know if the issue has gone on your ends.

Thanks, but... how? I'll have to wait for another :i386 package to be upgradeable to test it. As I have written down with printscreens, Webmin was able to install those packages just fine, and I don't want to revert those changes - I need audio. :(

**Comment by vinifmor** [comment]
It's ok... just install the staging branch, and when updates of these packages show up, give me a feedback. I'll let the issue opened.

**Comment by vinifmor** [comment]
I'll be closing the issue for now (since a unit test has been added to ensure the bug was fixed). Please, reopen it in case something similar happens.

**Comment by Templayer** [comment]
Testing now:

![image](https://user-images.githubusercontent.com/11728067/200504622-2d3f6c81-a03f-45c9-80fa-75c0a49b5ec3.png)

![image](https://user-images.githubusercontent.com/11728067/200504555-57b2fa84-f84f-4a95-9b1a-dd3cb41c41e1.png)

Seems to be fine:
[upgrade_2022118_1667894237_summary.txt](https://github.com/vinifmor/bauh/files/9958922/upgrade_2022118_1667894237_summary.txt)
[upgrade_2022118_1667894237.log](https://github.com/vinifmor/bauh/files/9958923/upgrade_2022118_1667894237.log)

**Comment by vinifmor** [comment]
Great... thanks for the feedback
