### ISSUE TITLE
really loving the fact i can resize the columns on this window????? thats the thickest sarcasm in case you didn't smell it!

### ISSUE THREAD

**Issue by Gridman44** [vinifmor/bauh#299]
![ArcoLinux-2022-10-26-1666824215_screenshot_5760x1848](https://user-images.githubusercontent.com/62721241/198153598-8776a677-4648-4021-b63d-fb7852222b9d.jpg)

**Comment by Templayer** [comment]
@Gridman44 Maybe if you didn't write it down as a twelve-year-old would...
