### ISSUE TITLE
Invalid script entry point

### ISSUE THREAD

**Issue by Ads20000** [vinifmor/bauh#3]
Got this error for `pip3 install bauh` on Ubuntu 19.04, any ideas?

```
Successfully built bauh
Installing collected packages: colorama, PyQt5-sip, pyqt5, requests, bauh
Invalid script entry point: <ExportEntry bauh = bauh.app:None []> for req: bauh - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.
```

```
$ apt show python3-pip
Version: 18.1-5
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
$ snap version
kernel  5.0.0-27-generic
```

**Comment by vinifmor** [comment]
Hello @Ads20000, I haven't got this before but I will test here for Ubuntu 19 and get back to you. In the meantime, try the manual installation via **virtualenv**. The process is described in the project **README** file. If you have any doubt in how to do it, post it here, please.

**Comment by vinifmor** [comment]
I have just installed a fresh Ubuntu 19.04 in a virtual machine and could install the application without problems using `sudo pip3 install bauh`. The **pip** version is the same as yours (**18.1-5**) and the **python3** version is **3.7.3-1**. What's your **python3** version ? Just a thought: it would be better to install the application in a **virtualenv** to not mess up with your system libraries.
