### ISSUE TITLE
Flatpack i368 packages are not shown properly in the GUI

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#303]
**Describe the bug**
i386 flatpack packages are not shown properly in the GUI. Probably because the GUI only parses the last part of the package name as a name for the package. If the package ends as ".i386" then the part before that (i.e. instead of using the part after the last dot, use the part after the preceding dot) should be the name in the GUI instead (with :i386 added, or something - let that be the same for all package managers, ideally).

![image](https://user-images.githubusercontent.com/11728067/203256831-a1bc2f96-0faf-4f8d-bc49-96a9994f52c4.png)

![image](https://user-images.githubusercontent.com/11728067/203255841-3d35b616-0112-47f5-b565-49244e7227d8.png)

They do seem to install properly, however. So it is only a visual issue (not knowing what I'm updating unless I actually proceed with the update).

[upgrade_20221122_1669103371_summary.txt](https://github.com/vinifmor/bauh/files/10065127/upgrade_20221122_1669103371_summary.txt)
[upgrade_20221122_1669103371.log](https://github.com/vinifmor/bauh/files/10065128/upgrade_20221122_1669103371.log)

Linked issue: https://github.com/vinifmor/bauh/issues/298

**Software Environment**
bauh version: 0.10.4 release
O.S name and version: Linux Mint 21
Python version: 3 :P
Installation method: pip

**Comment by vinifmor** [comment]
Hi @Templayer , I'll have a look here.

**Comment by vinifmor** [comment]
@Templayer I believe `i386` is how Flatpak returns the for the runtime `org.freedesktop.Platform.Compat.i386`. Please,  paste the output of `flatpak list -a` so we can confirm this.

**Comment by Templayer** [comment]
It's going to be weeks before I'll be able to do that, my shoulder is messed up and I've left my work laptop at work. :(

**Comment by vinifmor** [comment]
no worries... get well

**Comment by vinifmor** [comment]
Thanks for the feedback... I'll be closing the issue then.
