### ISSUE TITLE
[New AppImage] Inkscape

### ISSUE THREAD

**Issue by brccabral** [vinifmor/bauh#306]
- Application name: Inkscape
- Github page: https://gitlab.com/inkscape/inkscape
- Official website (if available): https://inkscape.org/

Inkspace is available at github.io , but it is not in apps.txt
https://appimage.github.io/Inkscape/

bauh search shows flapak and snap versions, but not appimage.

Is it possible to add Inkscape as appimage?

Thanks,
Bruno

**Comment by vinifmor** [comment]
Hi @brccabral , at the moment is not possible because the back-end relies on the GitHub's API. Also, the AppImage release should be available on the project's releases section.

**Comment by vinifmor** [comment]
Hi @brccabral I've added support for GitLab AppImages, but unfortunately inkscape does not attach the AppImage files to their GitLab releases (https://gitlab.com/inkscape/inkscape/-/releases).
