### ISSUE TITLE
Text too tiny

### ISSUE THREAD

**Issue by awsdert** [vinifmor/bauh#31]
I'm on manjaro x64 cinnamon and bauh doesn't load the system defaults or least doesn't honor them, everything else in my system loads fine so I think it's just bauh that's misbehaving, there is a ~/.cinnamon folder so there should also be docs relating to that to help you quick fix it

**Comment by vinifmor** [comment]
Hello @awsdert, bauh has it's own font settings int the current version. I'm sketching up a new interface that will fix this resolution issues.

**Comment by awsdert** [comment]
It's one thing to have internal settings available but to not by default honor the system settings is just bad UI design.
