### ISSUE TITLE
bauh gets stuck on "Downloading suggestions"

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#310]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11728067/210109429-588fa602-12f5-42b3-98cb-9eeb2ab6a7ed.png)

If "Synchronizing packages" fail (Mint's updater was just checking debians in the same moment), bauh gets stuck on "Downloading suggestions".

It cannot be skipped (the skip button doesn't work). It's been like this for over five minutes now, without a change, just the "progress bar" animating forward and back forever.

I was just going to update stuff, so I couldn't care less about debian suggestions not being available.

Expected behaviour - allow us to skip "Downloading suggestions".

And... now the skip button is available! It wasn't at first (even though every other topic was finished)!

Also - maybe there should be a grace period. If "Synchronizing packages" for debians fails the first time, wait for 5 seconds, then try again. Then wait for 15 seconds and try again. And if it fails then, fail it in bauh too. Unless you have a way of detecting that the system is checking them and thus they are unavailable.

**Software Environment**
![image](https://user-images.githubusercontent.com/11728067/210109856-daab2f5b-86ad-4682-bbf3-964cb978d14a.png)

**Comment by vinifmor** [comment]
Hi @Templayer , I'm going to reduce the waiting time for 10 seconds. It was actually on the backlog, but I forgot about it. Thanks for reporting it.

**Comment by Templayer** [comment]
> Hi @Templayer , I'm going to reduce the waiting time for 10 seconds. It was actually on the backlog, but I forgot about it. Thanks for reporting it.

Glad to be helpful. :)

**Comment by Prakash4844** [comment]
it only happens sometimes, generally restarting the app fixes it for me.
