### ISSUE TITLE
[New AppImage] Upscayl

### ISSUE THREAD

**Issue by bayazidbh** [vinifmor/bauh#319]
- Application name: Upscayl
- Github page: https://github.com/upscayl/upscayl
- Official website (if available): https://upscayl.github.io/

IMHO it's [major](https://old.reddit.com/r/linux/comments/wwbhtn/upscayl_linux_first_ai_image_upscaler/) [enough](https://old.reddit.com/r/linux/comments/zu64sk/upscayl_v2_is_out/) it's worth adding to database?

**Comment by vinifmor** [comment]
Thanks for the suggestion. I'll be available on the database after a few hours. If it doesn't show up, please, leave a comment on this issue.
