### ISSUE TITLE
Bauh does not show in app launcher and cannot add to favorites

### ISSUE THREAD

**Issue by Rik44444** [vinifmor/bauh#322]
Hi,
I'm loving Bauh, thanks for the dev! 
A question: Bauh is not showing in my application launcher and i cannot add it to my favorites in the dash either. 
Only way to launch it is via Alt-F2 and typing Bauh
is this intended behavior, or a bug?

--
Ubuntu Web 20.04.6 LTS 
Gnome 3.36.8

**Comment by Rik44444** [comment]
sorry this appears to be an Ubuntu Web issue

**Comment by vinifmor** [comment]
Hi @Rik44444 this depends on how bauh is installed on your system. Via pip there is no shortcut unfortunately. Via AUR or AppImage (you have to click on the "Self install" option via the hambuguer menu), it will generate the shortcut.
