### ISSUE TITLE
slow installs

### ISSUE THREAD

**Issue by Rik44444** [vinifmor/bauh#323]
Hi,
installs via Bauh take a LONG time on my pc (Lenovo T15 gen2, Ubuntu 20.04). 
Two suggestions:
1. see if things can be sped up (perhaps enable multi-threading by default...?)
2. like other app stores, show the users the various steps (e.g. "downloading app", "installing app" etc)

**Comment by vinifmor** [comment]
Hi @Rik44444 , when you say it's taking to long to install apps, could you point out the exact operation ? Because usually this is related to your configured repository mirrors (that can be sorted out by speed externally).
