### ISSUE TITLE
[New AppImage] nextcloud-desktop moved to another github web link

### ISSUE THREAD

**Issue by tuxfanmatze** [vinifmor/bauh#332]
- Application name: nextcloud-desktop
- Github page: https://github.com/nextcloud-releases/desktop/releases
- Official website (if available): https://nextcloud.com/install/

nextcloud-desktop has moved to another github link and unfortunately there is no download button for nextcloud-desktop at https://appimage.github.io/Nextcloud/.

But Nextcloud is a very well known app and originally supplied as an appimage.
So I hope you can again set it again to your install list.

**Comment by vinifmor** [comment]
I've just changed the links here. The updated database should be available in some hours. Thank you for sharing this.

**Comment by tuxfanmatze** [comment]
Thanks very much, it works now.

08.10.2023 16:27:27 Vinícius Moreira ***@***.***>:
