### ISSUE TITLE
trouble with getting text boxes to follow system theme

### ISSUE THREAD

**Issue by Ryder17z** [vinifmor/bauh#334]
**Describe the bug**

I cannot find a way to make bauh adhere to the system theme, unless i set bauh's theme to light and it just does not integrate fully with a dark system theme as the text boxes will then be white background with black text and everything else is pretty much the inverse.

Example: [image](https://github.com/vinifmor/bauh/assets/2000703/1ed89528-ccd1-42ad-9058-87fe55ef2523)

The alternative themes that I can select are a nice addition but none of them match the system theme that I have.

**Software Environment**
bauh version: 0.10.5 and 0.10.6 (staging branch)
O.S: Endeavor OS (Cassini Nova R3 using KDE 6)
Python version: 3.11.5
Installation method: yay

**Comment by vinifmor** [comment]
Hi... have you tried changing "Interface -> System Theme" to `Yes` ?

![bauh_systheme](https://github.com/vinifmor/bauh/assets/4312414/3fd4a964-18e4-4a92-b937-9e340257abdb)

**Comment by Ryder17z** [comment]
yeah. it doesn't help in my case

**Comment by vinifmor** [comment]
Alright... there is a previously opened [issue](https://github.com/vinifmor/bauh/issues/183) about this. I'm gonna close this one and link it to the other. Thanks for reporting the problem.
