### ISSUE TITLE
[Feature Request] In AUR package information page, add an AUR URL page

### ISSUE THREAD

**Issue by amethylghostling** [vinifmor/bauh#339]
This saves the user from having to type it himself which he will only be able to do if he knows the format of the AUR package URL so this is an essential feature. It is important to look at the AUR page to assess if a package is malicious or not or know what to add or remove into the PKGBUILD so that it succeeds in building if previously if failed to build.

**Software Environment**
bauh version: 0.10.6
O.S: name and version: EndeavourOS Cassini Nova (ArchLinux)
Python version: 3.11.6
Installation method: Pacman

**Comment by vinifmor** [comment]
just pushed it to the staging branch

**Comment by amethylghostling** [comment]
Thanks
