### ISSUE TITLE
[Feature Request] Make links clickable inside of Bauh

### ISSUE THREAD

**Issue by amethylghostling** [vinifmor/bauh#340]
For example in the package information page so that the user can just click on the link to open it if he wishes to, instead of having to copy it from bauh, then paste it into a web browser then hit enter.

**Software Environment**
bauh version: 0.10.6
O.S: name and version: EndeavourOS
Python version: 3.11.6
Installation method: Pacman

**Comment by vinifmor** [comment]
This feature is now available on the staging branch
