### ISSUE TITLE
How To Remove

### ISSUE THREAD

**Issue by kamishiro** [vinifmor/bauh#35]
I installed bauh following the manual instructions and all seemed to work, it opened and ran.
After I closed it, it won't open again "no such file or directory".
I would just like to remove it, however that too seems to have a major issue. 
$ pip3 uninstall bauh
Gives me several lines of exception errors
[bauh-error.txt](https://github.com/vinifmor/bauh/files/3897532/bauh-error.txt)

**Comment by vinifmor** [comment]
What distro are you currently using ? it seems the error is related to the Python configuration in your system.

If you did the manual procedure, to uninstall bauh just remove the  **env** folder created. I will update the README file in the next minor version that should come out this week.
