### ISSUE TITLE
Very confused on how to use bauh

### ISSUE THREAD

**Issue by dln949** [vinifmor/bauh#355]
Ubuntu 22.04.4, bauh 0.10.7

1)  When I first open bauh, it defaults to listing all applications - debian, snap, flatpak, and appimage, which is good.  But, I can't make the window wide enough to see the buttons on the right hand side of the window in each app's row.  The last button I can see is the "Uninstall" button, the rest are cutoff by bauh's window's right edge.  How do I resize the window to make it wider so I can see all the buttons and icons on the right side of each app's row?  I don't see any horizontal scrollbars.  (Under settings >> interface >> Scale (%) the lowest percentage allowed is 100%.  Auto scale does not appear to have any effect.)  

2)  How do I filter the initial list of all applications - no matter the package type - to show only those that have updates available?  

3)  For appimages:  I don't understand how the updating process is supposed to work:  For example, I currently have an older version of the balena-etcher appimage version 1.5 installed via bauh.  I know that the latest stable version on balena-etcher's github page is 1.18.  In bauh when I filter to show only Appimages, I see the installed balenaEtcher as an entry, along with some other appimages I have installed.  

     3.1)  How do I know which of the appimages listed have available upgrades?  I don't see any icon indicating that.  When I click on the "hamburger" icon for each appimage, I see that for balenaEtcher it says, "Upgrade file", but the other ones do not (because they are already the latest versions).  So, without having to click on each entry's icon, which would be tedious, how can I tell at a glance which appimage has an available upgrade to install?  

     3.2)  For balenaEtcher, when I click on the "hamburger" icon, it says, "Upgrade file".  When I click on the link that says, "Upgrade file", the "AppImage upgrade details" window appears, but that wants me to select a file that already exists on my local drive.  So, I am confused:  Is the idea that for appimages I am supposed to manually know about and find and download all upgrade appimage files and then bauh will install the upgrade from that downloaded file?  For some reason I _thought_ that bauh would work with Appimage Hub and it would first know that there is an upgrade available AND when I tell it to upgrade it would acquire that file and install it.  Is my thinking about this all wrong?  

I realize the odds are very high that the problem is that I'm just not figuring out the right way to make these things happen in bauh, which is why I submitted my questions using a blank template instead of as a bug.

**Comment by vinifmor** [comment]
Hi @dln949 
1. At the moment it's only possible through the upper maximize window button
2. bauh only displays the updates filter when there are any available
3. This issue might have happened during some of the database updates between `0.10.5` and `0.10.6`. If you reinstall your AppImage should solve the update problem.
3.1 bauh automatically displays updates for AppImages (if they were not manually imported)
3.2 this situation might be related to what I've answered on `3`
