### ISSUE TITLE
Install, manage & run Flatpak applications on standard user accounts

### ISSUE THREAD

**Issue by antoninchadima** [vinifmor/bauh#47]
The best way to run bauh with AppImage is without sudo from a standard user account.
This way you install your AppImage applications locally and you can run them from bauh as a standard user (recommended).
Everything for Appimage runs now in bauh OK - there is no problem.

I wish that Flatpak in bauh would behave the same way.
At this moment you need sudo to install Flatpak (maybe you could run bauh as a standard user by tweaking policykit...).
Flatpak applications are therefore installed globally and launched from the bauh GUI under the root user.

It would be nice to have the option to install Flatpak locally under the standard user.
It is done by appending the option --user in the CLI.
For example:
`flatpak install flathub org.mozilla.Thunderbird --user`
At the same time running bauh as a standard user would launch Flatpak applications as a standard user (recommended :-).

**Comment by antoninchadima** [comment]
I have checked the code. For user Flatpak installtation you should also:
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user`

**Comment by vinifmor** [comment]
Hi @antoninchadima . It is a good idea. I'm going to test this **--user** parameter and think the best approach for bauh.

**Comment by antoninchadima** [comment]
I'm using myself a modified version of bauh with the --user parameter for flatpak and i didn't find any issue yet.

**Comment by vinifmor** [comment]
Cool. I've been thinking about 3 approaches:

1. A dialog asking to the user if the app should be installed only for himself or for all users (system)
2. A config file where you could set the installation type: user or system
3. A mix of above

What do you think ?

**Comment by antoninchadima** [comment]
great work is done with pre 0.8.1
I like the way it is implemented

**Comment by vinifmor** [comment]
Thank you @antoninchadima . The official release is out. Let me know if you have any trouble.

**Comment by antoninchadima** [comment]
everything is OK
