### ISSUE TITLE
Support Protected Content in Web Apps (Widevine)

### ISSUE THREAD

**Issue by frpenguin** [vinifmor/bauh#49]
If I create a standalone web app for netflix.com or primevideo.com, for example, video does not play due to the lack of widevine. In my system (Arch) the package chromium-widevine is installed from the AUR and works fine with qutebrowser. Is there a posibility of doing the same for web apps created by bauh ?

**Comment by vinifmor** [comment]
Hi @frpenguin. I've seen this issue as well. It would be cool to have these apps supported by bauh. If I'm not mistaken, nativefier currently does not support widevine. But I will try to figure out a way to do that.

**Comment by frpenguin** [comment]
Hi @vinifmor. Thanks for the quick reply. Maybe through electron: https://electronjs.org/docs/tutorial/testing-widevine-cdm

**Comment by vinifmor** [comment]
Thanks for the docs, I will have a look here.

**Comment by vinifmor** [comment]
Done. You can now choose this new option on the installation window:
    <p align="center">
        <img src="https://raw.githubusercontent.com/vinifmor/bauh-files/master/pictures/releases/0.9.10/widevine.png">
    </p>

I've just published an RC to AUR (package: **bauh-staging**. version: **0.9.10.RC-1**)
