### ISSUE TITLE
No flatpak.yml

### ISSUE THREAD

**Issue by siduxdevil** [vinifmor/bauh#52]
I have this issue on two systems, both Debian Unstable based. I am using bauh 0.8.1. Flatpak works fine, I see my installed flatpaks and can handle them in any way supported. The issue is that I don't have a flatpak.yml under ~/.config/bauh. There is config.yml, appimage.yml and web.yml. 

Installed version of Flatpak is  1.6.0-1, Python is installed as  2.7.17 and 3.7.6. Bauh was installed per `sudo pip3 install bauh`. I rebooted both systems, but the file is still not there. What am I missing here?

**Comment by vinifmor** [comment]
I could reproduce here. The current version just creates the flatpak.yml when a new Flatpak app is installed through bauh. Could you confirm this ?

I can add a new behavior for the next minor forcing bauh to create the file during it's boot.

**Comment by siduxdevil** [comment]
I can confirm that flatpak.yml is created, even when trying to install a flatpak. Trying, because through bauh that is as far as I get. 

Trying to install as user I get: `Error: open(O_TMPFILE): Permission denied`, for system I get:` Warning: Failed to create a mountpoint for revokefs-fuse: Can't create temporary directory Error: Can't create temporary directory`.

**Comment by vinifmor** [comment]
Try to install at the user level. When bauh asks if you want to install for all users, choose "No". I believe the latest versions of Flatpak require root privileges to proper install at the system level. This issue already happened to me, but not always.

**Comment by siduxdevil** [comment]
I did as user and system. See above post.

**Comment by vinifmor** [comment]
My bad. I read fast and didn't notice. Well, it seems to be a system configuration issue. Are you able to install via command line without issues ? I've just launched a Linux Mint 18.3 VM on Virtual Box and had no issue installing an application at the user level. I'm going to make a little research about what can be happening on your system. Are you using a pure Debian system ?

**Comment by vinifmor** [comment]
Two topics related to user level:
https://github.com/flatpak/flatpak/issues/1507
https://github.com/flatpak/flatpak/issues/2808

**Comment by siduxdevil** [comment]
Siduction, based on Debian Unstable. I am one of the maintainers of siduction, it is 98% pure Debian, with our custom kernel.

**Comment by siduxdevil** [comment]
Problem fixed. Found the solution in the above mentioned[ flatpak issue](https://github.com/flatpak/flatpak/issues/2808). Setting permissions for /var/tmp to 1777 lets me install flatpaks through bauh in the user-context. Thanks for your time!

**Comment by vinifmor** [comment]
No worries. If you face more issues, let me know.
