### ISSUE TITLE
Feature suggestion: Manually install AppImages

### ISSUE THREAD

**Issue by lfom** [vinifmor/bauh#75]
bauh does a great job managing non-builtin distribution packages, but an option to manually install them would be great. For example, AppImageLauncher conflicts with bauh regarding appimages, so it must be uninstalled for bauh to work properly, but then there is no way to easily integrate an appimage that isn't available in one of the bauh sources, or maybe install a different version. 

An solution would be adding a menu option to manually install downloaded packages. Drag & drop support, both for the main window and icon, as well as support to open such files from the file manager (via mime-types, I guess), would be great.

Thanks again for the great work. Regards

**Comment by vinifmor** [comment]
Hello, @lfom . It is a nice suggestion and there is already an issue for this feature. I'm going to close this new and associated with the former. 

Regards.

**Comment by vinifmor** [comment]
https://github.com/vinifmor/bauh/issues/15
