### ISSUE TITLE
impossible install bauh error 

### ISSUE THREAD

**Issue by damiendenat** [vinifmor/bauh#85]
`damien@damien-X756UV:~$ bauh_env/bin/pip install bauh
Collecting bauh
  Using cached https://files.pythonhosted.org/packages/fc/f1/c85b9f78503f0653bb6d887cbf0eae8e6ea9c21f62cb72a7081e989472f5/bauh-0.8.5-py3-none-any.whl
Collecting requests>=2.18 (from bauh)
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting pyyaml>=3.13 (from bauh)
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Collecting colorama>=0.3.8 (from bauh)
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting pyqt5>=5.12 (from bauh)
  Using cached https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5uqsiuq_/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5uqsiuq_/pyqt5/
`
Anybody have a solution?

**Comment by vinifmor** [comment]
@damiendenat , what's your distro and its version ?

**Comment by damiendenat** [comment]
Ubuntu 18.04

**Comment by vinifmor** [comment]
Try to upgrade the **pip** and **setuptools** versions of the **bauh_env** before installing bauh:
```
bauh_env/bin/pip install pip --upgrade
bauh_env/bin/pip install setuptools --upgrade
bauh_env/bin/pip install bauh
```
If it doesn't work, try to install the **python3-venv** package and recreate the environment from the ground like this:
```
sudo apt install python3-venv
rm -rf bauh_env
virtualenv -p python3 bauh_env
bauh_env/bin/pip install pip --upgrade
bauh_env/bin/pip install setuptools --upgrade
bauh_env/bin/pip install bauh
```

**Comment by damiendenat** [comment]
It works
Merci beaucoup!

**Comment by vinifmor** [comment]
No worries. Cheers.
