### ISSUE TITLE
Internet connection needed

### ISSUE THREAD

**Issue by Ark-Shell** [vinifmor/bauh#88]
Hi!

I'm running bauh (german version) on Manjaro and it worked well until today when it tells me on every search "Internet connection needed". I have a connection and I can ask buah to refresh the mirrors or synchronise the database without any problem. But I can't search for any new software...

If I use pacman through command line it runs without any problem!

**Comment by vinifmor** [comment]
Hi @Ark-Shell , how many internet interfaces does your device has ? If you restart bauh the problem still happens ?

**Comment by vinifmor** [comment]
@Ark-Shell , try **bauh-staging** (0.9.1.RC-1) and let me know if the issue persists.

**Comment by Ark-Shell** [comment]
I have restarted bauh, uninstalled and installed it - it's still the same problem.
I habe 3 network interfaces, but only one of them is connected to the internet.

I'll try to install the bauh-staging.

**Comment by vinifmor** [comment]
@Ark-Shell, is it working for 0.9.1 ?

**Comment by Ark-Shell** [comment]
Sorry for coming back so late. It is indeed working with 0.9.1. Thank you!
