### ISSUE TITLE
no exit code - finish info for upgrades

### ISSUE THREAD

**Issue by AWHubGit** [vinifmor/bauh#89]
Running bauh in the GUI updating an AUR-App with "show details" there is no exit code anywhere or any other info if updating/upgrading has finished with success/fail.

Please add.

**Comment by vinifmor** [comment]
Already added and available in **bauh-staging** (0.9.1.RC-1)  from **AUR**

![aur_status](https://user-images.githubusercontent.com/4312414/79801274-32ada400-8334-11ea-8231-b16ca70e30df.png)

![aur_status_failed](https://user-images.githubusercontent.com/4312414/79801287-380aee80-8334-11ea-845b-bdd749b1dc0f.png)

**Comment by AWHubGit** [comment]
thanks
