### ISSUE TITLE
ModuleNotFoundError: No module named 'pip'

### ISSUE THREAD

**Issue by renestoe** [vinifmor/bauh#93]
this error occured while trying to upgrade Bauh 0.90

bauh_env/bin/pip install bauh --upgrade
Traceback (most recent call last):
  File "bauh_env/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

**Comment by renestoe** [comment]
i found a solution to this error:
i have to go to /bauh_env/bin/ and issue:
pip3 install bauh --upgrade

How can i issue this command in Bauh-upgrade.desktop file?

**Comment by vinifmor** [comment]
You can try to uninstall bauh first and them install it again. I've seen this before with some Python libraries.
```
bauh_env/bin/pip uninstall bauh -y
bauh_env/bin/pip install bauh
```
Also you could try to upgrade your pip and setuptools before reinstalling it:
```
bauh_env/bin/pip install pip --upgrade
bauh_env/bin/pip install setuptools --upgrade
```

I believe this command you executed (`pip3 install bauh --upgrade`) would install bauh locally on your system.

Would you like to issue the upgrade command through the desktop file ?
